mongodb/docs-java

source/includes/usage-examples/code-snippets/Find.java
source/includes/usage-examples/code-snippets/FindOne.java
source/includes/usage-examples/code-snippets/InsertMany.java
source/includes/usage-examples/code-snippets/InsertOne.java
source/includes/usage-examples/code-snippets/ReplaceOne.java
source/includes/usage-examples/code-snippets/UpdateOne.java
source/usage-examples/find.txt
source/usage-examples/insertMany.txt
source/usage-examples/insertOne.txt
source/usage-examples/replaceOne.txt
source/usage-examples/update-operations.txt
source/usage-examples/updateOne.txt

https://jira.mongodb.org/browse/DOCSP-9596
[replaceOne page](https://docs-mongodbcom-staging.corp.mongodb.com/e0d5956/java/docsworker-xlarge/DOCSP-9596-replace-one/usage-examples/replaceOne)
[updateOne update](https://docs-mongodbcom-staging.corp.mongodb.com/e0d5956/java/docsworker-xlarge/DOCSP-9596-replace-one/usage-examples/updateOne)
Note: the API links are currently broken as the 4.x docs appear to have been moved. Need to update the snooty toml once I confirm.

DOCSP-9596 replace one

---

source/includes/quick-start/gradle-versioned.rst
source/includes/quick-start/maven-versioned.rst
source/quick-start.txt

Reason for change:
- separate versioned snippets using the -versioned file suffix
- clarify a step that was a point of confusion
None
https://docs-mongodbcom-staging.corp.mongodb.com/91db077/java/docsworker-xlarge/113020-clarify-dependencies/quick-start
_- [ ] Are the staging links in the PR description updated?_

update versions, separate into files, and clarify dependency import process

---

source/includes/quick-start/atlas-setup.rst

None
https://docs-mongodbcom-staging.corp.mongodb.com/0a7c3dc/java/docsworker-xlarge/113020-link-fix/quick-start

fix atlas link in quickstart

---

source/fundamentals/crud.txt
source/fundamentals/crud/read.txt
source/fundamentals/crud/read/limit.txt

https://jira.mongodb.org/browse/DOCSP-9558
https://docs-mongodborg-staging.corp.mongodb.com/d2fdb0a/java/docsworker-xlarge/DOCSP-9558/fundamentals/crud/read/limit

DOCSP-9558: Fundamentals > CRUD Operations > Read Operations > Limit the Number of Returned Results

---

snooty.toml
source/fundamentals/builders.txt
source/fundamentals/builders/aggregates.txt
source/fundamentals/builders/filters.txt
source/fundamentals/builders/indexes.txt
source/fundamentals/builders/projections.txt
source/fundamentals/builders/sort.txt
source/fundamentals/builders/updates.txt

This adds a builders overview page. The page titles for the individual builders (work to be completed in other tickets) are verbose to avoid any user confusion, since there are multiple files named "indexes", for example.
https://jira.mongodb.org/browse/DOCSP-9582
https://docs-mongodbcom-staging.corp.mongodb.com/c634709/java/docsworker-xlarge/DOCSP-9582/fundamentals/builders

Docsp 9582

---

source/fundamentals/enterprise-auth.txt
source/includes/fundamentals/code-snippets/auth-credentials-gssapi-ticket-cache.rst

Document Kerberos default ticket caching behavior and how to configure Kerberos ticket caching by process. 
https://jira.mongodb.org/browse/DOCSP-13803
https://docs-mongodbcom-staging.corp.mongodb.com/2afd327/java/docsworker-xlarge/DOCSP-13803-kerberos-ticket-caching/fundamentals/enterprise-auth/#std-label-gssapi-auth-mechanism
* There is a warning that was present on master before making edits. Warning is:
`INFO:snooty.main:Snooty 0.9.2 starting
/usr/lib/python3.8/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.`
[From commit log from empty branch off of master](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=602d4284ab23346c2001f70d)

DOCSP-13803 Kerberos ticket caching

---

source/fundamentals/data-formats/document-data-format-extended-json.txt

Adds note about `$uuid` extended json type parsing.
https://jira.mongodb.org/browse/DOCSP-13806
https://docs-mongodbcom-staging.corp.mongodb.com/a0e24f5/java/docsworker-xlarge/DOCSP-13806/fundamentals/data-formats/document-data-format-extended-json/#extended-json-formats

DOCSP-13806: add note about $uuid parsing in extended json

---

source/fundamentals/builders/sort.txt

Create the Fundamentals > Builders > Sorts Page
https://jira.mongodb.org/browse/DOCSP-9585
https://docs-mongodbcom-staging.corp.mongodb.com/91154a2/java/docsworker-xlarge/DOCSP-9585-Fundamentals-Builders-Sort-Criteria/fundamentals/builders/sort/
Snooty Log Contains following Error which seems to be present on other branches as well. Possibly misreading build log but documenting here to check to discuss:
`ERROR(fundamentals/aggregation.txt:94ish): Target not found: "label:builders"
Closing connection...`

DOCSP-9585 builders sort criteria

---

source/fundamentals/builders/sort.txt
source/fundamentals/crud/read-operations/sort.txt

Migrate Fundamentals > Builders > Sorts page from  https://jira.mongodb.org/browse/DOCSP-9585 into Fundamentals > CRUD > Read > Sort and redo builders section to more explicitly focus on `Sorts` classs. 
https://jira.mongodb.org/browse/DOCSP-15135
https://docs-mongodbcom-staging.corp.mongodb.com/d9aff57/java/docsworker-xlarge/DOCSP-15135-CRUD-Read-Sort-Update/fundamentals/crud/read-operations/sort/
https://docs-mongodbcom-staging.corp.mongodb.com/d9aff57/java/docsworker-xlarge/DOCSP-15135-CRUD-Read-Sort-Update/fundamentals/builders/sort/

DOCSP-15135 crud read sort update

---

source/includes/usage-examples/code-snippets/FindOne.java

The find a document code example is sorting on an invalid field. Needs to sort on "imdb.rating" rather than "rating". 
NA
https://docs-mongodbcom-staging.corp.mongodb.com/fd85f1a/java/docsworker-xlarge/FindOne-Incorrect-Sort/usage-examples/findOne/

needs to sort on imdb.rating rather than rating

---

source/fundamentals/crud/compound-operations.txt

I accidentally merged in a build error with the compound operations page. This PR is to fix the build error. 
https://jira.mongodb.org/browse/DOCSP-16254
https://docs-mongodbcom-staging.corp.mongodb.com/2cad7af/java/docsworker-xlarge/DOCSP-16254-Fix-Build-Error/fundamentals/crud/compound-operations/
Build Log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60acf4b9f1f69374507ab158

DOCSP-16254 Fix Build Error

---

.gitignore
source/fundamentals/aggregation.txt
source/fundamentals/builders/aggregates.txt
source/includes/fundamentals/code-snippets/builders/AggBuilders.java
source/includes/fundamentals/code-snippets/builders/BuildersIntro.java

This adds the monstrously large aggregates builders page to the builders section.
https://jira.mongodb.org/browse/DOCSP-9586
https://docs-mongodbcom-staging.corp.mongodb.com/3a071f2/java/docsworker-xlarge/DOCSP-9586/fundamentals/builders/aggregates/

Docsp 9586

---

source/faq.txt
source/includes/fundamentals/code-snippets/CurrentAPI.java
source/includes/fundamentals/code-snippets/LegacyAPI.java
source/includes/legacy-redirect.rst
source/usage-examples/bulkWrite.txt
source/usage-examples/command.txt
source/usage-examples/count.txt
source/usage-examples/deleteMany.txt
source/usage-examples/deleteOne.txt
source/usage-examples/distinct.txt
source/usage-examples/find.txt
source/usage-examples/findOne.txt
source/usage-examples/insertMany.txt
source/usage-examples/insertOne.txt
source/usage-examples/replaceOne.txt
source/usage-examples/updateMany.txt
source/usage-examples/updateOne.txt
source/usage-examples/watch.txt

Add note to usage examples linking to FAQ entry that describes differences connecting to a MongoDB instance between the  current and legacy Java APIs.
https://jira.mongodb.org/browse/DOCSP-9930
https://docs-mongodbcom-staging.corp.mongodb.com/25fdd6e/java/docsworker-xlarge/DOCSP-9930-Legacy-API/faq/#how-do-i-connect-to-my-mongodb-instance-with-the-legacy-api-

Docsp 9930 legacy api

---

source/fundamentals/builders.txt
source/fundamentals/builders/filters.txt
source/fundamentals/builders/indexes.txt
source/fundamentals/builders/projections.txt
source/fundamentals/builders/sort.txt
source/fundamentals/builders/updates.txt

What was done in this PR:
1. Added the reason we use builders on the builders page
2. For each page, a general definition of builders and a link to the builders page
https://jira.mongodb.org/browse/DOCSP-15177
https://docs-mongodbcom-staging.corp.mongodb.com/ddb97d8/java/docsworker-xlarge/DOCSP-15177-BuildersDefinition/fundamentals/builders/
https://docs-mongodbcom-staging.corp.mongodb.com/ddb97d8/java/docsworker-xlarge/DOCSP-15177-BuildersDefinition/fundamentals/builders/filters/
https://docs-mongodbcom-staging.corp.mongodb.com/ddb97d8/java/docsworker-xlarge/DOCSP-15177-BuildersDefinition/fundamentals/builders/indexes/
https://docs-mongodbcom-staging.corp.mongodb.com/ddb97d8/java/docsworker-xlarge/DOCSP-15177-BuildersDefinition/fundamentals/builders/projections/ …

DOCSP-15177 definition of builders

---

source/fundamentals.txt
source/fundamentals/versioned-api.txt
source/includes/fundamentals/code-snippets/VersionedApiExample.java

https://jira.mongodb.org/browse/DOCSP-15781
https://docs-mongodbcom-staging.corp.mongodb.com/4d2fe1e/java/docsworker-xlarge/DOCSP-15781-versioned-api/fundamentals/versioned-api/
The API links assume that the `:java-docs:` target points to the 4.3 version. Currently, some of the links do not work because the `:java-docs:` target still points to the 4.2 version.

DOCSP-15781: Versioned API

---

source/fundamentals/builders/projections.txt

This removes the collection setup code block. It also adds a header for the section explaining variable names and the sample documents used. Lastly, upon examining the page I added another header and changed headers/section titles to be more consistent and better support the "On this page" widget.
https://jira.mongodb.org/browse/DOCSP-16496
https://docs-mongodbcom-staging.corp.mongodb.com/a2a5425/java/docsworker-xlarge/DOCSP-16496/fundamentals/builders/projections/

Remove collection setup code-block

---

source/fundamentals.txt
source/fundamentals/csfle.txt
source/includes/fundamentals/code-snippets/libmongocrypt-gradle-versioned.rst
source/includes/fundamentals/code-snippets/libmongocrypt-maven-versioned.rst

Add CSFLE guide to TOC. Update Mongo Crypt Version. Add basic style items as well like "On This Page" widget and "Overview" header.
https://jira.mongodb.org/browse/DOCSP-16557 (Retroactively Made)
https://docs-mongodbcom-staging.corp.mongodb.com/e20ccd0/java/docsworker-xlarge/add-CSFLE-guide/fundamentals/csfle/

Add csfle guide

---

source/includes/fundamentals/code-snippets/AggTour.java
source/includes/fundamentals/code-snippets/builders/Projections.java

Remove calls to `collection.drop()` when a collection name is not specified in the code snippet.
https://jira.mongodb.org/browse/DOCSP-16495
https://docs-mongodbcom-staging.corp.mongodb.com/8f73b74/java/docsworker-xlarge/DOCSP-16495-Collection-Drop/fundamentals/aggregation/

DOCSP-16495-Drop

---

source/fundamentals/aggregation.txt
source/fundamentals/auth.txt
source/fundamentals/builders/filters.txt
source/fundamentals/builders/projections.txt
source/fundamentals/builders/updates.txt
source/fundamentals/connection.txt
source/fundamentals/connection/tls.txt
source/fundamentals/crud/read-operations/geo.txt
source/fundamentals/crud/read-operations/sort.txt
source/fundamentals/crud/write-operations/insert.txt
source/fundamentals/data-formats/document-data-format-extended-json.txt
source/fundamentals/databases-collections.txt
source/fundamentals/indexes.txt
source/usage-examples.txt
source/usage-examples/command.txt
source/usage-examples/count.txt
source/usage-examples/deleteMany.txt
source/usage-examples/deleteOne.txt
source/usage-examples/insertMany.txt
source/usage-examples/insertOne.txt
source/usage-examples/replaceOne.txt
source/usage-examples/updateMany.txt
source/usage-examples/updateOne.txt
source/whats-new.txt

Fix Broken Links For Docs Release
https://jira.mongodb.org/browse/DOCSP-16488
https://docs-mongodbcom-staging.corp.mongodb.com/25ccaf3/java/docsworker-xlarge/DOCSP-16488-Broken-Links/
Some API links on the Versioned API Page Are expected not to work. See the [Versioned API PR](https://github.com/mongodb/docs-java/pull/87) For more details

Docsp 16488 broken links

---

source/fundamentals/indexes.txt

Removed rendered backticks -- only found on indexes page.
https://jira.mongodb.org/browse/DOCSP-16534
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-16534-backticks/fundamentals/indexes/

DOCSP-16534 fixed backticks

---

source/fundamentals/auth.txt
source/fundamentals/builders.txt
source/fundamentals/builders/aggregates.txt
source/fundamentals/connection.txt
source/fundamentals/connection/jndi.txt
source/fundamentals/connection/tls.txt
source/fundamentals/crud/read-operations/cursor.txt
source/fundamentals/crud/read-operations/project.txt
source/fundamentals/crud/read-operations/skip.txt
source/fundamentals/crud/write-operations/change-a-document.txt
source/fundamentals/crud/write-operations/upsert.txt
source/fundamentals/enterprise-auth.txt
source/fundamentals/gridfs.txt
source/fundamentals/monitoring.txt
source/fundamentals/versioned-api.txt
source/quick-start.txt

https://jira.mongodb.org/browse/DOCSP-16493
Note: I moved the overview section on the builders.txt page. No new content created although the diff may make it appear that way.
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-16493-overviews/

DOCSP-16493: add overview section to all fundamentals pages

---

source/fundamentals/auth.txt
source/fundamentals/connection.txt
source/fundamentals/connection/jndi.txt
source/fundamentals/connection/tls.txt
source/fundamentals/data-formats/codecs.txt
source/fundamentals/data-formats/document-data-format-bson.txt
source/fundamentals/data-formats/document-data-format-extended-json.txt
source/fundamentals/data-formats/document-data-format-pojo.txt
source/fundamentals/data-formats/documents.txt
source/fundamentals/data-formats/pojo-customization.txt
source/fundamentals/databases-collections.txt
source/fundamentals/enterprise-auth.txt
source/fundamentals/versioned-api.txt
source/includes/fundamentals/auth-specify.rst

Typos from start of fundamentals through Fundamentals > Data Formats
https://jira.mongodb.org/browse/DOCSP-16491
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-16491-Typos-Fundamentals/

Docsp 16491 typos fundamentals

---

source/fundamentals/builders.txt
source/fundamentals/builders/aggregates.txt
source/fundamentals/builders/filters.txt
source/fundamentals/builders/indexes.txt
source/fundamentals/builders/projections.txt
source/fundamentals/builders/updates.txt

Builders Section Typos
https://jira.mongodb.org/browse/DOCSP-16491
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-16491-Typos-After-Crud/fundamentals/builders/

Docsp 16491 typos after crud

---

source/compatibility.txt
source/faq.txt
source/fundamentals/aggregation.txt
source/fundamentals/gridfs.txt
source/fundamentals/indexes.txt
source/fundamentals/logging.txt
source/fundamentals/monitoring.txt
source/includes/fundamentals/code-snippets/IndexPage.java
source/includes/fundamentals/code-snippets/JMXMonitoring.java
source/issues-and-help.txt

Typos for pages after Fundamentals > Builders.
In order to expedite the final typo review PR, recently created fundamentals pages only had admonitions read for typos. The pages that were not read thoroughly in this review were:
- Collations
- GridFS
- Monitoring
https://jira.mongodb.org/browse/DOCSP-16491
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-16491-Typos-After-Builders/

Docsp 16491 typos after builders

---

source/fundamentals/connection.txt
source/includes/localhost-connection.rst
source/quick-start.txt

Added information about connecting to localhost on Quick Start and Connection.
Content is from what was done for the node-docs: https://github.com/mongodb/docs-node/pull/189 
https://jira.mongodb.org/browse/DOCSP-17190
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17190-localhostConnection/quick-start/#connect-to-localhost
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17190-localhostConnection/fundamentals/connection/#connect-to-localhost

DOCSP-17190 connecting to localhost

---

source/faq.txt
source/includes/quick-start/jdk-tls-issue.rst

Added TLS v1.3 error mentioned in the note box on quickstart (https://docs.mongodb.com/drivers/java/sync/quick-start/#query-your-mongodb-cluster-from-your-application) to the FAQ page.
https://jira.mongodb.org/browse/DOCSP-17059
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17059-TLSv1.3Error/faq/#how-do-i-fix---javax.net.ssl.sslhandshakeexception--extension--5--should-not-be-presented-in-certificate_request--

DOCSP-17059 TLS v1.3 error

---

source/whats-new.txt

https://jira.mongodb.org/browse/DOCSP-17548
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17548-serverless-mention/whats-new/

DOCSP-17548: mention serverless compatibility

---

source/fundamentals/crud/read-operations/geo.txt

I moved the figure after the code snippet so the user won't need any additional context.
https://jira.mongodb.org/browse/DOCSP-17577
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17577-GeoSpatialImage/fundamentals/crud/read-operations/geo/#query-within-a-range

DOCSP-17577 moved geospatial figure

---

source/fundamentals/connection/tls.txt
source/whats-new.txt

Client specific trust and key stores
https://jira.mongodb.org/browse/DOCSP-17220
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17220-Client-Specific-Key-Trust-Store/fundamentals/connection/tls/#configure-a-client-specific-trust-store-and-key-store

Docsp 17220 client specific key trust store

---

source/includes/fundamentals/code-snippets/GridFSOperations.java

Added the flush() method call to the upload a file using an output stream and download a file using an output stream section.
https://jira.mongodb.org/browse/DOCSP-17769
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17769-GridFGCodeExamples/fundamentals/gridfs/#upload-a-file-using-an-output-stream
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17769-GridFGCodeExamples/fundamentals/gridfs/#download-a-file-to-an-output-stream

DOCSP-17769 updated GridFS code examples

---

README.rst
source/api-documentation.txt
source/fundamentals/builders/filters.txt
source/fundamentals/builders/indexes.txt
source/fundamentals/builders/projections.txt
source/fundamentals/builders/sort.txt
source/fundamentals/builders/updates.txt
source/fundamentals/collations.txt
source/fundamentals/connection/jndi.txt
source/fundamentals/connection/tls.txt
source/fundamentals/crud/read-operations/sort.txt
source/fundamentals/crud/read-operations/text.txt
source/fundamentals/data-formats/document-data-format-bson.txt
source/fundamentals/logging.txt
source/index.txt
source/issues-and-help.txt
source/whats-new.txt

- Changed all http links to https 
- Updated instances of "Bson" to "BSON" 
Note: The only link not changed to http was slf4j link because it doesn't exist
https://jira.mongodb.org/browse/DOCSP-17770
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17770-httpsLinks/
Refer to the files tab to see all changes.

DOCSP-17770 https links and bson

---

source/fundamentals/enterprise-auth.txt
source/includes/fundamentals/code-snippets/auth-credentials-gssapi-subject-key.rst

Provide example of setting `JAVA_SUBJECT` property. The docs already [contain an admonition](https://github.com/mongodb/docs-java/blob/master/source/fundamentals/enterprise-auth.txt#L124-L135) informing readers that some properties can only be set through the `MongoCredential` class. 
https://jira.mongodb.org/browse/DOCSP-17095
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17095-JAVA_SUBJECT/fundamentals/enterprise-auth/#kerberos--gssapi-

Docsp 17095 java subject

---

source/fundamentals/crud/read-operations/cursor.txt

Updated the definition of the find method on the cursor page.
https://jira.mongodb.org/browse/DOCSP-17946
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17946-CursorPageFindDefinition/fundamentals/crud/read-operations/cursor/

DOCSP-17946 find method definition

---

source/quick-start.txt

As stated on the tin.
N/A
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=613920b8c608bec57f933cdd
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/remove-jdk-note/quick-start/

remove note about specifying jdk in pom.xml

---

source/index.txt

Implemented all bullets listed in the Jira ticket except for "Explain what a driver is (for all driver landing pages)" because I felt that saying `The official MongoDB Java driver lets you connect your Java applications to MongoDB and work with your data.` defines it. 
I also moved the M220 course to the bottom of the page under "Additional Learning".
Note: Some changes from our team PR meeting aren't implemented here because there is a [separate ticket](https://jira.mongodb.org/browse/DOCSP-18552) to edit sections overall after this one is complete. 
https://jira.mongodb.org/browse/DOCSP-18551
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=613bd63dc608bec57f54b583
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-18551-LandingPageImprovements/

DOCSP-18551 landing page improvements

---

source/fundamentals.txt
source/index.txt

Improved each landing page section by:
- adding each section of the API documentation
- putting the learning material + forums at the bottom of the page
Note: The leafy guy wasn't used since the visual design team asked us not to.
Also, I updated the fundamentals drawers page (to the landing page's fundamentals section) since I forgot to in my previous PR.
https://jira.mongodb.org/browse/DOCSP-18552
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6143a97ac608bec57fdfcdb0
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-18552-PageSectionsImprovements/
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-18552-PageSectionsImprovements/fundamentals/

DOCSP-18552 page sections improvements

---

source/fundamentals/collations.txt
source/fundamentals/enterprise-auth.txt

https://jira.mongodb.org/browse/DOCSP-18841
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6151fd108670bd2731065d4e
[Collation Options](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-18841-fixlinks/fundamentals/collations/#collation-options)
[Enterprise Auth](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-18841-fixlinks/fundamentals/enterprise-auth/)

DOCSP-18841: fix broken links

---

source/fundamentals/connection.txt

Added the `minPoolSize` connection option and updated the description for `maxPoolSize`.
https://jira.mongodb.org/browse/DOCSP-18917
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6160be268670bd2731adf692
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-18917-addingMinPoolSize/fundamentals/connection/#connection-options

DOCSP-18917 added minPoolSize

---

source/includes/quick-start/gradle-versioned.rst

`compile` is deprecated or removed, so now we use `implementation`.
https://jira.mongodb.org/browse/DOCSP-19395
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61800d2ec13055282daf2388
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-19395/quick-start/

compile -> implementation for gradle

---

snooty.toml
source/fundamentals/connection/mongoclientsettings.txt

Changes of note:
- Renamed Java -> Java Sync in snooty.toml for proper breadcrumb display (differentiate it from Java RS)
- Added setting (ticket task) [srvMaxHosts](https://github.com/mongodb/docs-java/pull/174/files#diff-b33e95fb0e2b3cd27f170a41ded73770cdd15a0beabcaa7cfc938e7827b8f1ebR238-R244)
- Removed zero-width space characters and trailing spaces in source/fundamentals/connection/mongoclientsettings.txt 
- Removed stray single-quotation mark https://github.com/mongodb/docs-java/pull/174/files#diff-b33e95fb0e2b3cd27f170a41ded73770cdd15a0beabcaa7cfc938e7827b8f1ebL315
https://jira.mongodb.org/browse/DOCSP-19171
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6181b2acc13055282d15a5cc
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-19171-mong …

DOCSP-19171: max hosts setting

---

source/fundamentals/connection/tls.txt

This documents how to use Netty for TLS/SSL. 🔥 The API docs link will not work on master as the 4.4 API docs aren't published, but it will work on 4.3.
https://jira.mongodb.org/browse/DOCSP-17234
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6184028fc13055282dab7e2d
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17234/fundamentals/connection/tls/#configure-netty

Docsp 17234

---

source/index.txt

https://jira.mongodb.org/browse/DOCSP-19656
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=619c2f085314b0809fe4fe21
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-19656-remove-release-notes/

DOCSP-19656: remove release notes link

---

snooty.toml

I forgot to remove the `beta` tag from the `full-version` constant when 4.4 was released.
n/a
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=619d1b405314b0809f1a7ad9
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/nl-remove-beta-tag/quick-start/#add-mongodb-as-a-dependency

remove beta tag

---

source/fundamentals/logging.txt

Update version of log4j recommended in the docs to a version patched for https://nvd.nist.gov/vuln/detail/CVE-2021-44228
Recommended this version: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-slf4j-impl/2.15.0
None
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61b38133c52f2a460f5c11df
https://docs-mongodborg-staging.corp.mongodb.com/java/docsworker-xlarge/NNNNNNNNNNN/

update recommended log4j version

---

source/fundamentals/logging.txt

Update Log4J dependency to 2.16.0 for security reasons.
https://github.com/mongodb/docs-java/pull/190#issuecomment-994406845
None
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61b9ff0dc52f2a460fce642f
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/121521-update-log4j/fundamentals/logging/

Update Log4J dependency to 2.16.0

---

source/fundamentals/logging.txt

Update log4j2 dependency mention to 2.17.0
Addresses https://nvd.nist.gov/vuln/detail/CVE-2021-45105?s=09
None
https://jira.mongodb.org/browse/DOCSP-NNNNN
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61c0a065c52f2a460f547d0a
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/122021-log4j2-version/fundamentals/logging/#example---set-up

log4j2 version update

---

source/fundamentals/logging.txt

Fix version for https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2327339
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61d46d6241accb3633a9bd6f
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/010421-log4j-update/fundamentals/logging/#example---set-up

update log4j to 2.17.1

---

.github/workflows/checker.yml
snooty.toml
source/fundamentals/connection/connection-options.txt

Exposes `maxConnecting`. This has been split from the original PR since that content needs to be seen by more eyes since it is prescriptive in connection tuning.
It also adds in a checker with github actions.
https://jira.mongodb.org/browse/DOCSP-19628
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61d71ae241accb36335bad85
https://docs-mongodborg-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-19628-slim/

Docsp 19628 slim

---

source/fundamentals/data-formats/pojo-customization.txt
source/includes/mongodb-compatibility-table-java.rst

https://jira.mongodb.org/browse/DOCSP-19966
Fixed constructor name and clarified annotation usage.
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61e70bcabcf82347e52b6b8d
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-19966-annotation-fix/fundamentals/data-formats/pojo-customization/#annotations

DOCSP-19966: fix pojo constructor and annotation description

---

snooty.toml
source/compatibility.txt

During a meeting it was noticed that the Java compat table page wasn't uniform with other pages.
N/A
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=620bcc83382d7fe4ee3c0565
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/unify-compat-table/compatibility/

Unify-compat-table

---

source/quick-start.txt

N/A
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=621d47d59c4c7f6bfb4d98b3
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/add-ref/quick-start/

add ref to java quickstart

---

source/fundamentals/connection/connection-options.txt

Add default values for all connection options
https://jira.mongodb.org/browse/DOCSP-20825
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=622692521a622fb274228ad9
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-20825-Connection-Defaults/fundamentals/connection/connection-options/

(DOCSP-20825) Connection Defaults

---

source/fundamentals/monitoring.txt

Fixed the link for `TraceMongoCommandListener`.
After the PR is approved, I'll cherry pick to v4.4 and v4.5.
https://jira.mongodb.org/browse/DOCSP-22040
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=625882af0fdfea9c371287cd
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-22040-LinkFix/fundamentals/monitoring/#include-the-driver-in-your-distributed-tracing-system

DOCSP-22040 link fix

---

snooty.toml
source/fundamentals/indexes.txt
source/usage-examples/watch.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-22817
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-22817-walltime/usage-examples/watch/#example
For the change listed in the JIRA ticket A/C, see the output after: 
"Only the insert and update operations are printed, since the aggregation pipeline filters out the delete operation:"
For the link fixes to autobuilder errors present in the current master branch, see "Clustered Index" and "Clustered Collections":
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-22817-walltime/fundamentals/indexes/#clustered-indexes

DOCSP-22817: add walltime to changedocument output

---

source/fundamentals/data-formats/pojo-customization.txt
source/includes/fundamentals/code-snippets/optional-codec-provider/Address.java
source/includes/fundamentals/code-snippets/optional-codec-provider/ApplicationUser.java
source/includes/fundamentals/code-snippets/optional-codec-provider/OptionalPropertyCodecProvider.java
source/includes/fundamentals/code-snippets/optional-codec-provider/OptionalPropertyExample.java
source/includes/fundamentals/code-snippets/optional-codec-provider/Subscription.java

The code appears to be working in the current driver version, but for ease of testing, I created an example app to allow user testing of the functionality and sourced the Codec code in the docs.
JIRA - https://jira.mongodb.org/browse/DOCSP-23217
Staging -
[Scroll down from this section header to verify the OptionalPropertyCodecProvider code snippet shows up as intended](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-23217-add-codecprovider-example/fundamentals/data-formats/pojo-customization/#generics-support)

DOCSP-23217: Add OptionalPropertyCodecProviderExample for testing

---

source/fundamentals/indexes.txt
source/upgrade.txt
source/whats-new.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-23045
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-23045-setwindowfields-api-update/whats-new/#what-s-new-in-4.7
The link checker is failing on a link that loads when accessed through a browser.

DOCSP-23045: add setWindowFields API change to release notes

---

source/fundamentals/indexes.txt
source/upgrade.txt
source/whats-new.txt

* DOCSP-23045: add setWindowFields API change in release notes
(cherry picked from commit 3f0b43cdc6de69affbc4f7a048bd20e4d9aa34d6)
JIRA - https://jira.mongodb.org/browse/DOCSP-NNNNN
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/

DOCSP-23045: add setWindowFields API change to release notes (#245)

---

source/upgrade.txt

(cherry picked from commit 9830df3ff0dcf0e3560b4a93e0036447e7c3b610)
https://github.com/mongodb/docs-java/pull/249
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62f12944230aeb802e5e17bc

Backport: typo fix

---

source/fundamentals/builders/aggregates.txt

Original link and description were correct for 4.6. New link and description for 4.7.
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/081622-fix-broken-link/fundamentals/builders/aggregates/#setwindowfields

081622: update builder link and link description

---

source/fundamentals/data-formats.txt
source/fundamentals/data-formats/codecs.txt
source/fundamentals/data-formats/document-data-format-pojo.txt
source/fundamentals/data-formats/document-data-format-record.txt
source/fundamentals/data-formats/pojo-customization.txt
source/includes/fundamentals/code-snippets/records/CodecRecordExample.java
source/includes/fundamentals/code-snippets/records/DataStorageRecord.java
source/whats-new.txt

- Removed inaccurate information about withCodecRegistry method existing on MongoClient
- Added ref targets
- Set lowercase "p" in "plain old Java objects"
- JIRA - https://jira.mongodb.org/browse/DOCSP-22293
- Given the similarities of the Records Page and the [POJOs page](https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/data-formats/document-data-format-pojo/), I plan to ticket future work to determine the best way to organize the information to reduce duplication. This page doesn't contain as much detail as the POJOs page, but directs to other pages that should help the reader locate the omitted info.
- Link checker failure is a false positive, created a [JIRA …

DOCSP-22293: Records and Codec Provider

---

source/fundamentals/builders/updates.txt
source/fundamentals/collations.txt
source/fundamentals/crud/read-operations/limit.txt
source/fundamentals/data-formats/documents.txt
source/fundamentals/data-formats/pojo-customization.txt

No JIRA ticket
This PR fixes the code-block rST indentation which silently failed to apply syntax highlighting for the specified language. While it's beyond expectations to review each file, to verify the syntax highlighting is applied, you'll need to individually inspect each code block with Chrome Tools for the "java" (or other) style in the code component:
Staging:
[Builders: Updates](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/110922-test-highlight-fix/fundamentals/builders/updates/)
[Collations](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/110922-test-highlight-fix/fundamentals/collations/)
[Read Operations: …

Syntax highlighting fix

---

snooty.toml
source/upgrade.txt
source/whats-new.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-24606
Moved Server Release Compatibility changes to the bottom since the driver breaking changes are more common. Made sure that there's a link from the driver version breaking change entry to the server compatibility changes.
Staging:
[What's new](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-24606-3.6-unsupported/whats-new/#what-s-new-in-4.8)
[v4.8 Breaking changes](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-24606-3.6-unsupported/upgrade/#version-4.8-breaking-changes)

DOCSP-24606: add info about v4.8 server breaking change and upgrading

---

source/fundamentals/connection.txt

This will backport the following commits from `master` to `v4.6`:

[v4.6] DOCSP-27932: add AWS Lambda connection guide link (#317)

---

source/fundamentals/connection.txt

This will backport the following commits from `master` to `v4.4`:

[v4.4] DOCSP-27932: add AWS Lambda connection guide link (#317)

---

source/fundamentals/connection.txt

This will backport the following commits from `master` to `v4.3`:

[v4.3] DOCSP-27932: add AWS Lambda connection guide link (#317)

---

source/fundamentals/connection.txt

This will backport the following commits from `master` to `v4.8`:

[v4.8] DOCSP-27932: add AWS Lambda connection guide link (#317)

---

source/fundamentals/connection.txt

This will backport the following commits from `master` to `v4.7`:

[v4.7] DOCSP-27932: add AWS Lambda connection guide link (#317)

---

source/fundamentals/connection.txt

This will backport the following commits from `master` to `v4.5`:

[v4.5] DOCSP-27932: add AWS Lambda connection guide link (#317)

---

source/fundamentals/crud/read-operations/sort.txt

JIRA - No official ticket, but related to https://jira.mongodb.org/browse/DOCSP-28477
Staging 
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/030923-api-link-fix/fundamentals/crud/read-operations/sort/#text-search
> "For more information, see the Sorts class API Documentation."

Fix broken API link

---

source/whats-new.txt

Added as release note only (see comments to Jira ticket). 
Modeled on 4.7.1 update on the same page.
JIRA - https://jira.mongodb.org/browse/DOCSP-21335
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/docsp-21335-nxdomain-error/whats-new/#std-label-version-4.5.1

DOCSP-21335 - 4.5.1 Release Note

---

source/upgrade.txt

JIRA - https://jira.mongodb.org/browse/DOCS-15368
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/docs-15368-clarify-uuid/upgrade/

DOCS-15368 - Clarify UUID changes

---

source/fundamentals/crud/read-operations/change-streams.txt
source/includes/fundamentals/code-snippets/change-streams/ChangeStreams.java

JIRA - [DOCSP-22867](https://jira.mongodb.org/browse/DOCSP-22867)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-22867-describe-changestreamdocument/fundamentals/crud/read-operations/change-streams/#example)

DOCSP-22867: describe ChangeStreamDocument

---

source/fundamentals/crud/read-operations/change-streams.txt
source/includes/fundamentals/code-snippets/change-streams/ChangeStreams.java

JIRA - [DOCSP-30151](https://jira.mongodb.org/browse/DOCSP-30151)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-15810-update-cs-example/fundamentals/crud/read-operations/change-streams/)

DOCSP-15810: update changestream page to use new feature + cleanup

---

source/faq.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-26368
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-26368-FAQ-illegalstateexception/faq/#how-do-i-prevent-the--illegalstateexception--state-should-be--open--error-

DOCSP-26368: FAQ entry for state should be open exception

---

source/upgrade.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-31894
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-31894-fix-href/upgrade/

DOCSP-31894: fix href

---

source/includes/fundamentals/code-snippets/MongoDbAwsAuth.java
source/includes/fundamentals/code-snippets/auth-credentials-default.rst
source/includes/fundamentals/code-snippets/auth-credentials-gssapi.rst
source/includes/fundamentals/code-snippets/auth-credentials-ldap.rst
source/includes/fundamentals/code-snippets/auth-credentials-sha1.rst
source/includes/fundamentals/code-snippets/auth-credentials-sha256.rst
source/includes/fundamentals/code-snippets/auth-credentials-x509.rst

JIRA - https://jira.mongodb.org/browse/DOCSP-32129
Note: in some instances, the "atlasUri" placeholder was replaced by "hostname" since an Atlas URI likely contains more information than just the hostname, and would therefore error according to the [API documentation](https://mongodb.github.io/mongo-java-driver/4.10/apidocs/mongodb-driver-core/com/mongodb/ServerAddress.html#%3Cinit%3E(java.lang.String)).
Staging:
[Authentication Mechanisms](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-32129-fix-serveraddress-port-placeholder/fundamentals/auth/) - select MongoCredential tab to see the relevant code snippets.
[Enterprise Authentication …

DOCSP-32129: fix ServerAddress placeholder for port parameter

---

source/faq.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-26370
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-26370-faq-mongosecurityexception/faq/#how-do-i-prevent-the--com.mongodb.mongosecurityexception--error-

DOCSP-26370: FAQ entry for MongoSecurityException

---

source/fundamentals/auth.txt
source/includes/fundamentals/code-snippets/MongoDbAwsAuth.java

JIRA - https://jira.mongodb.org/browse/DOCSP-32565
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-32565-correct-refresh-example/fundamentals/auth/#std-label-mongodb-aws-auth-mechanism
Make sure MongoCredential tab is selected and review the last code example.

DOCSP-32565: Fix the AWS refresh credentials example

---

config/redirects
source/fundamentals/crud/write-operations.txt
source/fundamentals/crud/write-operations/delete.txt
source/fundamentals/crud/write-operations/modify.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-31823
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-31823-update-titles/fundamentals/crud/write-operations/modify/>
<https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-31823-update-titles/fundamentals/crud/write-operations/delete/>
Redirects - 
Redirect 301 /docs/drivers/java/sync/v4.3/fundamentals/crud/write-operations/change-a-document/ https://www.mongodb.com/docs/drivers/java/sync/v4.3/fundamentals/crud/write-operations/modify/
Redirect 301 /docs/drivers/java/sync/v4.4/fundamentals/crud/write-operations/change-a-document/ https://www.mongodb.com/docs/drivers/java/sync/v4.4/fundamentals …

DOCSP-31823: updated page titles

---

source/fundamentals/crud/write-operations/bulk.txt
source/includes/fundamentals/code-snippets/BulkWrite.java

JIRA - https://jira.mongodb.org/browse/DOCSP-31089
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-31089-fix-bulk-examples/fundamentals/crud/write-operations/bulk/

DOCSP-31089: Improve bulk operation examples

---

source/legacy.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-31430
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-31430-new-sync-features/legacy/

DOCSP-31430: Explain new API benefits

---

source/fundamentals/connection/mongoclientsettings.txt

- Fixed the format of the connection string in the Chain Order example
- Removed the tip that provided redundant information.
- Vale fixes
JIRA - none
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/091423-fix-malformed-connection-uri/fundamentals/connection/mongoclientsettings/#example

091423: fix malformed connection uri on MongoClientSettings page

---

source/fundamentals/data-formats/document-data-format-extended-json.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-33241
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/java/DOCSP-33241-extended-json-example-fix/fundamentals/data-formats/document-data-format-extended-json/#extended-json-examples

DOCSP-33241: fix extended JSON example id field

---

source/fundamentals/aggregation-expression-operations.txt

The "$first" and "$last" links in the linked staging site should take you to the correct locations in the Server manual
Note: there are several Vale errors, but skipping for now since this is a quick link fix rather than a content one.
JIRA - https://jira.mongodb.org/browse/DOCSP-33300
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/java/DOCSP-33300-fix-agg-links/fundamentals/aggregation-expression-operations/

DOCSP-33300: Fix aggregation operator links to the manual

---

source/fundamentals/crud/read-operations/change-streams.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-31907
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-31907-split-event/fundamentals/crud/read-operations/change-streams/#split-large-change-stream-events

DOCSP-31907 Split Event

---

source/fundamentals/crud/read-operations/change-streams.txt

Adding a paragraph to the Split Change Stream events section per tech review ([commented on another PR](https://github.com/mongodb/docs-java/pull/457#:~:text=View%20reviewed%20changes-,source/fundamentals/crud/read%2Doperations/change%2Dstreams.txt,-%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D))
JIRA - https://jira.mongodb.org/browse/DOCSP-31907
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/java/DOCSP-31907-split-event-add-note/fundamentals/crud/read-operations/change-streams/#split-large-change-stream-events

DOCSP-31907 - Add paragraph from server docs

---

source/fundamentals/builders/aggregates.txt
source/includes/fundamentals/code-snippets/builders/AggBuilders.java

Note: as mentioned on the ticket, do not merge this until after the feature is released with MongoDB 6.0.11 and 7.0.2.
Note: all the TODOs should be resolved after the API docs are published and before merging.
JIRA - https://jira.mongodb.org/browse/DOCSP-33234
Staging:
- [List of static imports updated](https://preview-mongodbcchomongodb.gatsbyjs.io/java/DOCSP-33234-vector-search/fundamentals/builders/aggregates/#overview)
- [vectorSearch section](https://preview-mongodbcchomongodb.gatsbyjs.io/java/DOCSP-33234-vector-search/fundamentals/builders/aggregates/#atlas-vector-search)

DOCSP-33234: add vectorSearch builder

---

source/includes/usage-examples/code-snippets/BulkWrite.java
source/includes/usage-examples/code-snippets/Command.java
source/includes/usage-examples/code-snippets/CountDocuments.java
source/includes/usage-examples/code-snippets/DeleteMany.java
source/includes/usage-examples/code-snippets/DeleteOne.java

Staging:
Bulk write - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-1/usage-examples/bulkWrite/
Run command - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-1/usage-examples/command/
Count - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-1/usage-examples/count/
DeleteOne - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-1/usage-examples/deleteOne/
DeleteMany - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-1/usage-examples/deleteMany/

DOCSP-33345: Java code comments pt. 1

---

source/includes/usage-examples/code-snippets/Distinct.java
source/includes/usage-examples/code-snippets/Find.java
source/includes/usage-examples/code-snippets/FindOne.java
source/includes/usage-examples/code-snippets/InsertMany.java
source/includes/usage-examples/code-snippets/InsertOne.java

Staging:
Distinct - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-2/usage-examples/distinct/
Find - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-2/usage-examples/find/
FindOne - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-2/usage-examples/findOne/
InsertMany - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-2/usage-examples/insertMany/
InsertOne - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-2/usage-examples/insertOne/

DOCSP-33345: Java code comments pt. 2

---

source/includes/fundamentals/code-snippets/GridFSOperations.java
source/includes/fundamentals/code-snippets/IndexPage.java
source/includes/fundamentals/code-snippets/Insert.java
source/includes/fundamentals/code-snippets/InsertUpdate.java
source/includes/fundamentals/code-snippets/JMXMonitoring.java

Staging:
GridFS - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-6/fundamentals/gridfs/
IndexPage - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-6/fundamentals/indexes/
Insert - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-6/fundamentals/crud/write-operations/insert/
InsertUpdate - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-6/fundamentals/crud/write-operations/upsert/
Monitoring - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-6/fundamentals/monitoring/

DOCSP-33345: Java comments pt. 6

---

source/includes/fundamentals/code-snippets/JsonFormats.java
source/includes/fundamentals/code-snippets/LegacyAPI.java
source/includes/fundamentals/code-snippets/MongoDbAwsAuth.java

Staging:
JSON - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-7/fundamentals/data-formats/document-data-format-extended-json/
Legacy API - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-7/faq/
AWS Auth - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-7/fundamentals/auth/#std-label-mongodb-aws-auth-mechanism

DOCSP-33345: Java comments pt. 7

---

source/includes/fundamentals/code-snippets/Monolight.java
source/includes/fundamentals/code-snippets/MonolightCodec.java
source/includes/fundamentals/code-snippets/Query.java

Staging:
Codecs - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-8/fundamentals/data-formats/codecs/
Queries - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-8/fundamentals/crud/query-document/

DOCSP-33345: Java comments pt. 8

---

source/includes/fundamentals/code-snippets/Retrieve.java
source/includes/fundamentals/code-snippets/SearchText.java
source/includes/fundamentals/code-snippets/Skip.java

Staging:
Retrieve - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-9/fundamentals/crud/read-operations/retrieve/
Text search - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-9/fundamentals/crud/read-operations/text/
Skip - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-9/fundamentals/crud/read-operations/skip/

DOCSP-33345: Java comments pt. 9

---

source/includes/fundamentals/code-snippets/CurrentAPI.java
source/includes/fundamentals/code-snippets/Cursor.java
source/includes/fundamentals/code-snippets/Delete.java
source/includes/fundamentals/code-snippets/Filters.java
source/includes/fundamentals/code-snippets/Geo.java

Staging:
CurrentAPI - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-5/faq/
Cursor - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-5/fundamentals/crud/read-operations/cursor/
Delete - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-5/fundamentals/crud/write-operations/delete/
Filters - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-5/fundamentals/builders/filters/
Geo - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-5/fundamentals/crud/read-operations/geo/

DOCSP-33345: Java comments pt. 5

---

source/includes/fundamentals/code-snippets/TimeSeries.java
source/includes/fundamentals/code-snippets/Update.java
source/includes/fundamentals/code-snippets/UpdateArray.java

Staging:
Time series - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-10/fundamentals/time-series/
Update - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-10/fundamentals/crud/write-operations/modify/
Update array - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-33345-java-comments-10/fundamentals/crud/write-operations/embedded-arrays/

DOCSP-33345: Java comments pt. 10

---

source/fundamentals/connection/tls.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-33943
Staging - [Enable TLS/SSL](https://preview-mongodbcchomongodb.gatsbyjs.io/java/DOCSP-33943-tls-when-using-seedlist/fundamentals/connection/tls/#enable-tls-ssl)

DOCSP-33943: mention dns seedlist default tls setting

---

source/includes/usage-examples/code-snippets/Command.java

JIRA - https://jira.mongodb.org/browse/DOCSP-34069
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/java/DOCSP-34069-fix-run-command-usage-example/usage-examples/command/

DOCSP-34069: fix imports for run command usage example

---

source/connection-troubleshooting.txt
source/faq.txt
source/fundamentals/aggregation.txt
source/fundamentals/auth.txt
source/fundamentals/builders/aggregates.txt
source/fundamentals/builders/filters.txt
source/fundamentals/connection/tls.txt
source/fundamentals/crud/read-operations/cursor.txt
source/fundamentals/crud/write-operations/bulk.txt
source/fundamentals/data-formats/pojo-customization.txt
source/fundamentals/enterprise-auth.txt
source/fundamentals/logging.txt
source/issues-and-help.txt
source/usage-examples/bulkWrite.txt
source/usage-examples/command.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-33951>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-33951-javasync-alas/

DOCSP-33951: atomic typos fy2024-q4

---

source/fundamentals/builders/sort.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-31340>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-31340/fundamentals/builders/sort/>

[Java] - Improve Sort Builder page sample data

---

source/fundamentals/connection/mongoclientsettings.txt
source/includes/fundamentals/code-snippets/mcs.java
source/upgrade.txt
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-34994>
**this PR also includes content for the removal described in [DOCSP-34104](https://jira.mongodb.org/browse/DOCSP-34104)**
Staging:
- [whats new](https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-34994-clustersettings-types-fix/whats-new/)
- [upgrade guide](https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-34994-clustersettings-types-fix/upgrade/)
- [example](https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-34994-clustersettings-types-fix/fundamentals/connection/mongoclientsettings/#example-5)

DOCSP-34994: socketsettings parameter types fix

---

source/upgrade.txt
source/whats-new.txt

This is a Java 5.0 ticket.
JIRA - <https://jira.mongodb.org/browse/DOCSP-35011>
Staging:
https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-35011-connectionid-return-types/whats-new/
https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-35011-connectionid-return-types/upgrade/#std-label-java-breaking-changes-v5.0

DOCSP-35011: ConnectionId class changes

---

source/upgrade.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-35304>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-35304-remove-fulleq/upgrade/#version-5.0-breaking-changes

DOCSP-35304: remove eqFull method

---

source/compatibility.txt
source/fundamentals/aggregation.txt
source/includes/fact-environments.rst
source/includes/fundamentals/code-snippets/AggTour.java
source/index.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-33664>
**[Staging](https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-33664-fix-agg-code/fundamentals/aggregation/#explain-aggregation-example)**

DOCSP-33664: fix explain agg code + other fixes

---

source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-35270>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-35270/whats-new/#std-label-version-5.0>

[JAVA] Relax the CMAP documentation requirement for durations in events

---

snooty.toml

JIRA - <https://jira.mongodb.org/browse/DOCSP-35626>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/v4.6/

DOCSP-35626: eol v4.6

---

config/redirects

I noticed the Connection Troubleshooting page only exists for v4.9 and newer.
JIRA - None
Staging - None
New redirects generated by mut-redirects:
```
Redirect 301 /docs/drivers/java/sync/v4.3/connection-troubleshooting/ https://www.mongodb.com/docs/drivers/java/sync/v4.3/
Redirect 301 /docs/drivers/java/sync/v4.4/connection-troubleshooting/ https://www.mongodb.com/docs/drivers/java/sync/v4.4/
Redirect 301 /docs/drivers/java/sync/v4.5/connection-troubleshooting/ https://www.mongodb.com/docs/drivers/java/sync/v4.5/
Redirect 301 /docs/drivers/java/sync/v4.6/connection-troubleshooting/ https://www.mongodb.com/docs/drivers/java/sync/v4.6/
Redirect 301 …
```

011124: fix redirect for connection troubleshooting up to v4.8

---

REVIEWING.md

Updated guidance to ensure writers understand that they should get tech reviews for changes that include release notes and breaking changes.
JIRA - None
Staging - None

011924: update review recommendations to improve guidance

---

source/fundamentals/data-formats/document-data-format-pojo.txt
source/fundamentals/data-formats/pojo-customization.txt
source/includes/fundamentals/code-snippets/POJO-class-example.java
source/includes/fundamentals/code-snippets/POJO-crud.java

JIRA - <https://jira.mongodb.org/browse/DOCSP-22844>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-33844-pojo-examples/fundamentals/data-formats/document-data-format-pojo/

DOCSP-22844: POJO CRUD examples

---

source/quick-start.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-35821>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-35821-link-jar-file/quick-start/#add-mongodb-as-a-dependency

DOCSP-35821: link to jar download

---

source/connection-troubleshooting.txt
source/upgrade.txt

Note to the reviewer:
I think the review could be focused on checking the indentation. The autobuilder doesn't currently report all code-block errors, but the indentation prior to the changes looks incorrect.
Ignoring Vale issues and tags for now since this is an RST formatting-only bug fix.
JIRA - None
Staging:
- [Upgrade](https://preview-mongodbcchomongodb.gatsbyjs.io/java/020724-fix-indentation/upgrade/)
- [Connection Troubleshooting](https://preview-mongodbcchomongodb.gatsbyjs.io/java/020724-fix-indentation/connection-troubleshooting/)

020724 fix indentation

---

snooty.toml
source/fundamentals/collations.txt
source/upgrade.txt
source/whats-new.txt

Replaces #510 
JIRA - https://jira.mongodb.org/browse/DOCSP-34103
JIRA - https://jira.mongodb.org/browse/DOCSP-34106
JIRA - https://jira.mongodb.org/browse/DOCSP-34107
JIRA - https://jira.mongodb.org/browse/DOCSP-34108
JIRA - https://jira.mongodb.org/browse/DOCSP-34104
JIRA - https://jira.mongodb.org/browse/DOCSP-34115
JIRA - https://jira.mongodb.org/browse/DOCSP-34116
JIRA - https://jira.mongodb.org/browse/DOCSP-34317
JIRA - https://jira.mongodb.org/browse/DOCSP-34128
JIRA - https://jira.mongodb.org/browse/DOCSP-34140
Staging
- [What's New](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/mikefork/whats-new/#std-label-version-5.0)
- …

5.0 Removals - Rebase

---

source/fundamentals/databases-collections.txt
source/upgrade.txt
source/whats-new.txt

JIRA 
- <https://jira.mongodb.org/browse/DOCSP-35762>
- Java work: https://jira.mongodb.org/browse/JAVA-4353
Staging
- [What's New](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-35762/whats-new/#what-s-new-in-5.0)
- [Breaking Changes](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-35762/upgrade/#version-5.0-breaking-changes)

[Java] Document breaking changes to listCollectionName methods and new authorizedCollections method

---

source/upgrade.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-35704>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-35704/upgrade/#version-5.0-breaking-changes>

[JAVA] Uncomment reference to Scala API docs after they are released

---

source/connection-troubleshooting.txt
source/upgrade.txt

Changes:
- Link fix
- Adds placeholder introduced in [this PR](https://github.com/10gen/docs-shared/pull/66/files).
JIRA - None
Staging:
- [Link fix](https://preview-mongodbcchomongodb.gatsbyjs.io/java/031324-fix-link/upgrade/#version-5.0-breaking-changes)
- [Connection Troubleshooting build fix](https://preview-mongodbcchomongodb.gatsbyjs.io/java/031324-fix-link/connection-troubleshooting/#check-the-credentials-formatting) (no visible content)

031324: fix link

---

source/whats-new.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-38612
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-38612-3.6-deprecation/whats-new/#std-label-version-5.1

DOCSP-38612: MongoDB v3.6 deprecation

---

source/upgrade.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-39430>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-39430-server-8.0-incompat/upgrade/#server-release-compatibility-changes>

DOCSP-39430: server 8.0 support change

---

source/fundamentals/crud/read-operations/geo.txt
source/includes/fundamentals/code-snippets/Geo.java

JIRA - https://jira.mongodb.org/browse/DOCSP-38823
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-38823-insert-doc-geospatial/fundamentals/crud/read-operations/geo/

DOCSP-38823: Insert docs with geospatial data

---

source/connection-troubleshooting.txt
source/fundamentals/connection/connection-options.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-30349>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-30349-server-sel-errors/connection-troubleshooting/#server-selection-timeout-exceptions

DOCSP-30349: server selection errors

---

source/fundamentals/connection/connect.txt
source/whats-new.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-40537
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/java/DOCSP-40537-connection-optional-slash/whats-new/#std-label-version-5.2

DOCSP-40537 Optional delimiting slash in connection string

---

source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-41030>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-41030-proxy-domain-name-validation/whats-new/#std-label-java-new-features-4.11
**will port to 5.0, 5.1, master**

DOCSP-41030: proxy domain name validation

---

source/index.txt
source/validate-signatures.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-39555>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-39555-jvm-validate-sigs/validate-signatures/

DOCSP-39555: java driver sig verification

---

source/fundamentals/data-formats/pojo-customization.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-40062
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-40062-fix-annotation/fundamentals/data-formats/pojo-customization/

DOCSP-40062: BsonProperty getters/setters

---

source/fundamentals/connection/connection-options.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-41593>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-41593-connopts-typo/fundamentals/connection/connection-options/#:~:text=Default%3A%200-,maxIdleTimeMS,-integer

DOCSP-41593: typo fix

---

source/fundamentals/monitoring.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-40830>
Staging - <https://preview-mongodbstephmarie17.gatsbyjs.io/java/DOCSP-40805-loadBalancedModeUpdate/fundamentals/monitoring/#server-discovery-and-monitoring-events>

DOCSP-40830 Include load balanced mode note

---

source/connection-troubleshooting.txt
source/fundamentals/auth.txt
source/fundamentals/connection/mongoclientsettings.txt
source/fundamentals/connection/network-compression.txt
source/fundamentals/connection/tls.txt
source/fundamentals/enterprise-auth.txt
source/fundamentals/indexes.txt
source/includes/faq/code-snippets/FaqExample.java
source/includes/fundamentals/code-snippets/auth-credentials-default.rst
source/includes/fundamentals/code-snippets/auth-credentials-gssapi-properties.rst
source/includes/fundamentals/code-snippets/auth-credentials-gssapi-subject-key.rst
source/includes/fundamentals/code-snippets/auth-credentials-gssapi-ticket-cache.rst
source/includes/fundamentals/code-snippets/auth-credentials-gssapi.rst
source/includes/fundamentals/code-snippets/auth-credentials-ldap.rst
source/includes/fundamentals/code-snippets/auth-credentials-sha1.rst
source/includes/fundamentals/code-snippets/auth-credentials-sha256.rst
source/includes/quick-reference/QuickReferenceSnippets.java
source/quick-start.txt
source/usage-examples.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-42372>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/java/DOCSP-42372-username-password/>

DOCSP-42372: Change username and password placeholders

---

snooty.toml
source/fundamentals/builders/aggregates.txt
source/fundamentals/indexes.txt
source/includes/fundamentals/code-snippets/SearchIndexMethods.java
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-42282>
Staging - 
[indexes](https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-42282-searchindex-type/fundamentals/indexes/#create-a-search-index)
[whats new](https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-42282-searchindex-type/whats-new/#std-label-java-version-5.2)

DOCSP-42282: java avs index type support

---

source/whats-new.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-38784
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-38784-add-back/whats-new/#std-label-java-version-5.2

DOCSP-38784: Sharded cluster retries

---

source/fundamentals.txt
source/fundamentals/transactions.txt
source/includes/fundamentals/code-snippets/Transaction.java

JIRA - <https://jira.mongodb.org/browse/DOCSP-41762>
Staging - <https://deploy-preview-569--docs-java.netlify.app/fundamentals/transactions/>

DOCSP-41762 Add transactions page

---

source/connection-troubleshooting.txt

JIRA - https://jira.mongodb.org/browse/DOCS-16861
Staging - https://deploy-preview-576--docs-java.netlify.app/connection-troubleshooting/#monitor-thread-exception

Update troubleshooting guidance

---

snooty.toml

JIRA - https://jira.mongodb.org/browse/DOCSP-43975
Staging - https://deploy-preview-579--docs-java.netlify.app/

DOCSP-43975: EOL docs versions

---

source/fundamentals/connection/mongoclientsettings.txt
source/fundamentals/data-formats/pojo-customization.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-42961 
Staging - <https://deploy-preview-581--docs-java.netlify.app/>

DOCSP-42961: Removed Nested Components

---

source/whats-new.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-43934
Staging - https://deploy-preview-588--docs-java.netlify.app/whats-new/#what-s-new-in-5.2.1

DOCSP-43934 Add OSGi fix to what's new

---

.github/workflows/backport.yml
source/fundamentals.txt
source/fundamentals/builders.txt
source/fundamentals/connection.txt
source/fundamentals/crud.txt
source/fundamentals/crud/read-operations.txt
source/fundamentals/crud/write-operations.txt
source/fundamentals/data-formats.txt
source/index.txt
source/usage-examples.txt
source/usage-examples/delete-operations.txt
source/usage-examples/find-operations.txt
source/usage-examples/insert-operations.txt
source/usage-examples/update-operations.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-44901>

[Backport v5.1] DOCSP-44901 Shorten TOC

---

source/quick-start.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-45218
Staging - https://deploy-preview-598--docs-java.netlify.app/quick-start/#add-mongodb-as-a-dependency

DOCSP-45218 - Clarify build tool language

---

source/fundamentals/data-formats/codecs.txt

After investigating this ticket with the Java engineer, the decision was to leave the codec example as-is, but fix a bug on the page
JIRA - https://jira.mongodb.org/browse/DOCSP-29939
Staging - https://deploy-preview-605--docs-java.netlify.app/fundamentals/data-formats/codecs/#codecregistry

DOCSP-29939 Codec example fix

---

source/fundamentals/transactions.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-45872>
Staging - <https://deploy-preview-606--docs-java.netlify.app/fundamentals/transactions/>

DOCSP-45872: Parallel operations note

---

.github/workflows/vale-tdbx.yml
source/fundamentals/crud/write-operations/bulk.txt
source/whats-new.txt

JIRA - [DOCSP-41769](https://jira.mongodb.org/browse/DOCSP-41769)
Staging:
- https://deploy-preview-590--docs-java.netlify.app/fundamentals/crud/write-operations/bulk/ (note at the beginning, then "Improved Bulk Write Command" and onward)
- https://deploy-preview-590--docs-java.netlify.app/whats-new

DOCSP-41769: Improved bulk write API

---

source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-44667>
Staging - https://deploy-preview-607--docs-java.netlify.app/whats-new/#what-s-new-in-5.3

DOCSP-44667: bson vector subtype

---

source/fundamentals/data-formats/pojo-customization.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-44656>
Staging - <https://deploy-preview-612--docs-java.netlify.app/fundamentals/data-formats/pojo-customization/>

[Java Sync] Typo fix to phrasing

---

source/includes/fundamentals/code-snippets/Monitoring.java
source/logging-monitoring/monitoring.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-47042>
<li><a href=https://deploy-preview-633--docs-java.netlify.app/logging-monitoring/monitoring>logging-monitoring/monitoring</a></li>

DOCSP-47042 Monitoring Edits

---

source/connection/connect.txt

**Note:** This information won't render correctly until the [docs-shared PR](https://github.com/10gen/docs-shared/pull/93) is merged.
JIRA - https://jira.mongodb.org/browse/DOCSP-47044
<li><a href=https://deploy-preview-646--docs-java.netlify.app/connection/connect>connection/connect</a></li>

DOCSP-47044: Polling DNS SRV records

---

source/connection/connection-options.txt
source/connection/mongoclientsettings.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-47271>
<li><a href=https://deploy-preview-645--docs-java.netlify.app/connection/connection-options>connection/connection-options</a></li><li><a href=https://deploy-preview-645--docs-java.netlify.app/connection/mongoclientsettings>connection/mongoclientsettings</a></li>

DOCSP-47271 Mention SOCKS5 Proxy Guide

---

source/security/auth/oidc.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-47923>
<li><a href=https://deploy-preview-640--docs-java.netlify.app/security/auth/oidc>security/auth/oidc</a></li>

DOCSP-47923 Kubernetes for OIDC

---

source/atlas-search.txt
source/includes/AtlasSearch.java

JIRA - https://jira.mongodb.org/browse/DOCSP-47824
<li><a href=https://deploy-preview-625--docs-java.netlify.app/atlas-search>atlas-search</a></li>

DOCSP-47824: Atlas search

---

source/security/auth/aws-iam.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-48053>
<li><a href=https://deploy-preview-653--docs-java.netlify.app/security/auth/aws-iam>security/auth/aws-iam</a></li>

[JAVA] Update AWS SDK dependencies

---

source/integrations.txt
source/issues-and-help.txt

Adds missing meta descriptions generated by the Education AI Team\n\nSOURCE: https://docs.google.com/spreadsheets/d/1fdrjF4Ms9fMl96zLiLGsYD_V38rTfPLuKs5VQk4vz6E/edit?gid=1166644539

Add missing meta descriptions

---

source/security/encrypt-fields.txt

Moved QE Connection Settings to Server docs ([PR](https://github.com/10gen/docs-mongodb-internal/pull/11665))
JIRA - <https://jira.mongodb.org/browse/DOCSP-49143>
<li><a href=https://deploy-preview-673--docs-java.netlify.app/security/encrypt-fields>security/encrypt-fields</a></li>

DOCSP-49143 - Remove duplicate H1s

---

source/connection/specify-connection-options/csot.txt
source/crud/gridfs.txt
source/includes/connect/CsotExample.java

JIRA - <https://jira.mongodb.org/browse/DOCSP-35922>
- [csot page](https://deploy-preview-683--docs-java.netlify.app/connection/specify-connection-options/csot/#gridfs)
- [gridfs page tip](https://deploy-preview-683--docs-java.netlify.app/crud/gridfs/#overview)

DOCSP-35922: csot - gridfs

---

source/connection/specify-connection-options/cluster-settings.txt

Missed during Comprehensive Coverage
JIRA - N/A
[connection/specify-connection-options/cluster-settings/](https://deploy-preview-678--docs-java.netlify.app/connection/specify-connection-options/cluster-settings/)

Add loadBalanced connection option

---

config/redirects
source/index.txt
source/reference.txt
source/reference/legacy.txt
source/reference/release-notes.txt

Backport #698 to v5.1

---

source/data-formats/document-data-format-bson.txt
source/includes/fundamentals/code-snippets/bson-gradle-versioned.rst
source/includes/fundamentals/code-snippets/bson-maven-versioned.rst
source/includes/fundamentals/code-snippets/crypt-gradle-versioned.rst
source/includes/fundamentals/code-snippets/crypt-maven-versioned.rst
source/security/encrypt-fields.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-49013>
<li><a href=https://deploy-preview-706--docs-java.netlify.app/data-formats/document-data-format-bson>data-formats/document-data-format-bson</a></li><li><a href=https://deploy-preview-706--docs-java.netlify.app/security/encrypt-fields>security/encrypt-fields</a></li>

DOCSP-49013-BOM Tips for Java Sync

---

source/data-formats/codecs.txt

This will backport the following commits from `master` to `v5.5`:
- [DOCSP-50736 update title Java Codec](https://github.com/mongodb/docs-java/pull/716)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

[v5.5] DOCSP-50736 update title Java Codec

---

config/redirects

This will backport the following commits from `master` to `v5.5`:
- [Merge pull request #718 from mballard-mdb/DOCSP-50728-duplicate-metadata-bulk](https://github.com/mongodb/docs-java/pull/718)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

[v5.5] Merge pull request #718 from mballard-mdb/DOCSP-50728-duplicate-metadata-bulk

---

config/redirects

This will backport the following commits from `master` to `v5.4`:
- [Merge pull request #718 from mballard-mdb/DOCSP-50728-duplicate-metadata-bulk](https://github.com/mongodb/docs-java/pull/718)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

[v5.4] Merge pull request #718 from mballard-mdb/DOCSP-50728-duplicate-metadata-bulk
