source/usage-examples.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-9589
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/404f553/java/docsworker-xlarge/DOCSP-9589-usage-examples-landing/usage-examples
=> DOCSP-9589: Usage Examples landing page

source/includes/usage-examples/code-snippets/InsertOne.java, source/usage-examples.txt, source/usage-examples/insert-operations.txt, source/usage-examples/insertOne.txt
https://jira.mongodb.org/browse/DOCSP-9592
https://docs-mongodbcom-staging.corp.mongodb.com/64bcad4/java/docsworker-xlarge/DOCSP-9592-insert-one/usage-examples/insertOne
=> DOCSP-9592: Usage Examples - insertOne

source/includes/usage-examples/code-snippets/UpdateOne.java, source/usage-examples.txt, source/usage-examples/insertOne.txt, source/usage-examples/update-operations.txt, source/usage-examples/updateOne.txt
https://jira.mongodb.org/browse/DOCSP-9594
https://docs-mongodborg-staging.corp.mongodb.com/4f504ee/java/docsworker-xlarge/DOCSP-9594-update-one/usage-examples/updateOne
=> DOCSP-9594: Java updateOne Usage Example

source/includes/usage-examples/code-snippets/Distinct.java, source/usage-examples.txt, source/usage-examples/distinct.txt
https://jira.mongodb.org/browse/DOCSP-9600
https://docs-mongodbcom-staging.corp.mongodb.com/4fb9ca5/java/docsworker-xlarge/DOCSP-9600-distinct-usage-example/usage-examples/distinct
=> DOCSP-9600 distinct usage example

source/includes/usage-examples/code-snippets/CountDocuments.java, source/usage-examples.txt, source/usage-examples/count.txt
https://jira.mongodb.org/browse/DOCSP-9599
https://docs-mongodbcom-staging.corp.mongodb.com/701d590/java/docsworker-xlarge/DOCSP-9599-count-usage-example/usage-examples/count
=> DOCSP-9599 count usage example

source/includes/usage-examples/code-snippets/UpdateMany.java, source/usage-examples/update-operations.txt, source/usage-examples/updateMany.txt
https://jira.mongodb.org/browse/DOCSP-9595
https://docs-mongodbcom-staging.corp.mongodb.com/6a98491/java/docsworker-xlarge/DOCSP-9595-update-multiple/usage-examples/updateMany
=> DOCSP-9595: Update Multiple usage example

source/includes/usage-examples/code-snippets/FindOne.java, source/includes/usage-examples/code-snippets/InsertMany.java, source/includes/usage-examples/code-snippets/InsertOne.java, source/includes/usage-examples/code-snippets/UpdateOne.java, source/includes/usage-examples/code-snippets/deleteOne.java, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/deleteOne.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/updateOne.txt
https://jira.mongodb.org/browse/DOCSP-9597
https://docs-mongodbcom-staging.corp.mongodb.com/4d2fd18/java/docsworker-xlarge/DOCSP-9597-delete-one/usage-examples/deleteOne
=> DOCSP-9597 delete one

source/includes/usage-examples/code-snippets/DeleteMany.java, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/deleteMany.txt, source/usage-examples/insertMany.txt
https://jira.mongodb.org/browse/DOCSP-9598
https://docs-mongodbcom-staging.corp.mongodb.com/9f877ca/java/docsworker-xlarge/DOCSP-9598-delete-many/usage-examples/deleteMany
=> DOCSP-9598: delete many usage example

source/issues-and-help.txt
https://jira.mongodb.org/browse/DOCSP-9605
https://docs-mongodbcom-staging.corp.mongodb.com/ffeb6f2/java/docsworker-xlarge/DOCSP-9605-issues-help/issues-and-help
=> DOCSP-9605: issues and help page

source/includes/usage-examples/code-snippets/Command.java, source/usage-examples.txt, source/usage-examples/command.txt
https://jira.mongodb.org/browse/DOCSP-9601
https://docs-mongodbcom-staging.corp.mongodb.com/18cb1fc/java/docsworker-xlarge/DOCSP-9601/usage-examples/command
=> (DOCSP-9601): Usage Examples > Run a Command

source/includes/usage-examples/code-snippets/Watch.java, source/includes/usage-examples/code-snippets/WatchCompanion.java, source/usage-examples.txt, source/usage-examples/watch.txt
https://jira.mongodb.org/browse/DOCSP-9602
https://docs-mongodborg-staging.corp.mongodb.com/50be17a/java/docsworker-xlarge/DOCSP-9602/
=> Docsp 9602

source/fundamentals/connection.txt, source/fundamentals/connection/tls.txt
Inspired by Jeff Yemin's feedback on https://github.com/mongodb/docs-java/pull/24
https://jira.mongodb.org/browse/DOCSP-9551
https://docs-mongodbcom-staging.corp.mongodb.com/0508062/java/docsworker-xlarge/jyeminConnectionFeedback/fundamentals/connection
https://docs-mongodbcom-staging.corp.mongodb.com/0508062/java/docsworker-xlarge/jyeminConnectionFeedback/fundamentals/connection/tls
=> Connection Refinement

source/fundamentals/auth.txt, source/includes/fundamentals/code-snippets/auth-credentials-x509.rst
Addresses comments in [prematurely-merged PR](https://github.com/mongodb/docs-java/pull/25)
https://jira.mongodb.org/browse/DOCSP-9552
https://docs-mongodbcom-staging.corp.mongodb.com/ca26f7c/java/docsworker-xlarge/DOCSP-9552-fixes-auth-mechanisms/fundamentals/auth
=> DOCSP-9552: fixes to auth mechanisms page

.github/pull_request_template.md
https://jira.mongodb.org/browse/DOCSP-NNNN
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/java/docsworker-xlarge/NNNNNNNNNNN/
=> update the pull request template with a self-review checklist

source/fundamentals/data-formats/document-data-format-bson.txt, source/fundamentals/data-formats/document-data-format-pojo.txt
https://jira.mongodb.org/browse/DOCSP-12159
https://docs-mongodborg-staging.corp.mongodb.com/056c933/java/docsworker-xlarge/DOCSP-12159-fundamentals-pojo/fundamentals/data-formats/document-data-format-pojo
=> DOCSP-12159: Data Formats POJOs

source/fundamentals/auth.txt
=> correction in auth mech

source/fundamentals/auth.txt, source/includes/fundamentals/code-snippets/auth-credentials-aws-session.rst
https://jira.mongodb.org/browse/DOCSP-13488
https://docs-mongodbcom-staging.corp.mongodb.com/2ef8c5a/java/docsworker-xlarge/DOCSP-13488-mongodb-aws-updates/fundamentals/auth#std-label-mongodb-aws-auth-mechanism
=> Docsp 13488 mongodb aws updates

source/includes/fundamentals/code-snippets/auth-credentials-aws-session.rst, source/includes/fundamentals/code-snippets/auth-credentials-aws.rst
Applied a change similar to:
https://github.com/mongodb/mongo-java-driver/pull/615#discussion_r534427031
None
https://docs-mongodbcom-staging.corp.mongodb.com/502aebe/java/docsworker-xlarge/120420-char-array/fundamentals/auth#mongodb-aws
=> use toCharArray for password

source/fundamentals/crud/sort.txt
https://jira.mongodb.org/browse/DOCSP-9557
https://docs-mongodborg-staging.corp.mongodb.com/960a4dd/java/docsworker-xlarge/DOCSP-9557/fundamentals/crud/sort
=> DOCSP-9557: Fundamentals > CRUD Operations > Read Operations > Sort Results

source/fundamentals/data-formats/document-data-format-pojo.txt, source/fundamentals/data-formats/pojo-customization.txt
https://jira.mongodb.org/browse/DOCSP-9550
https://docs-mongodbcom-staging.corp.mongodb.com/e69ddf4/java/docsworker-xlarge/DOCSP-9550-pojo-customization/fundamentals/data-formats/pojo-customization
- The :java-docs: directive points to 4.2 rather than 4.1
=> DOCSP-9550 POJO customization

source/index.txt, source/whats-new.txt
https://jira.mongodb.org/browse/DOCSP-9547
https://docs-mongodbcom-staging.corp.mongodb.com/12e296f/java/docsworker-xlarge/DOCSP-9547-WhatsNewPage/whats-new/
=> DOCSP-9547 whats new page

source/fundamentals.txt, source/fundamentals/indexes.txt, source/includes/fundamentals/code-snippets/IndexPage.java
Adding coverage for indexes. A link to the builders page will be added as part of that PR.
https://jira.mongodb.org/browse/DOCSP-9555
https://docs-mongodbcom-staging.corp.mongodb.com/1bf9dff/java/docsworker-xlarge/DOCSP-9555/fundamentals/indexes/
=> DOCSP-9555: indexes

source/fundamentals.txt, source/fundamentals/aggregation.txt, source/fundamentals/builders/projections.txt, source/fundamentals/data-formats/document-data-format-bson.txt, source/includes/fundamentals/code-snippets/builders/Projections.java
Projections builders.
https://jira.mongodb.org/browse/DOCSP-9584
https://docs-mongodbcom-staging.corp.mongodb.com/de17980/java/docsworker-xlarge/DOCSP-9584/fundamentals/builders/projections/
=> DOCSP-9584: projections

source/fundamentals/crud.txt, source/fundamentals/crud/query-document.txt, source/includes/fundamentals/code-snippets/Query.java
https://jira.mongodb.org/browse/DOCSP-9567
https://docs-mongodbcom-staging.corp.mongodb.com/f259a2c/java/docsworker-xlarge/DOCSP-9567-CRUDQuery/fundamentals/crud/query-document/
=> DOCSP-9567 crud query

source/fundamentals/crud/write-operations.txt, source/fundamentals/crud/write-operations/delete.txt, source/includes/fundamentals/code-snippets/Delete.java
https://jira.mongodb.org/browse/DOCSP-15338
https://docs-mongodbcom-staging.corp.mongodb.com/7d04861/java/docsworker-xlarge/DOCSP-15338-CRUDDelete/fundamentals/crud/write-operations/delete/
=> DOCSP-15338 crud delete

source/fundamentals.txt, source/fundamentals/collations.txt, source/includes/fundamentals/code-snippets/CollationCollectionExample.java
https://jira.mongodb.org/browse/DOCSP-9574
https://docs-mongodbcom-staging.corp.mongodb.com/d3c6811/java/docsworker-xlarge/DOCSP-9574-collations/fundamentals/collations/
=> DOCSP-9574: Collations

source/fundamentals/crud/write-operations/upsert.txt, source/includes/fundamentals/code-snippets/InsertUpdate.java
https://jira.mongodb.org/browse/DOCSP-9565
https://docs-mongodbcom-staging.corp.mongodb.com/a058a77/java/docsworker-xlarge/DOCSP-9565-CRUDUpsert/fundamentals/crud/write-operations/upsert/
=> DOCSP-9565 crud upsert

source/fundamentals/crud/write-operations.txt, source/fundamentals/crud/write-operations/change-a-document.txt, source/includes/fundamentals/code-snippets/Update.java
https://jira.mongodb.org/browse/DOCSP-15337
https://docs-mongodbcom-staging.corp.mongodb.com/a4be427/java/docsworker-xlarge/DOCSP-15337-CRUDUpdate/fundamentals/crud/write-operations/change-a-document/
=> DOCSP-15337 crud update

source/fundamentals/crud/read-operations/cursor.txt, source/includes/fundamentals/code-snippets/Cursor.java
https://jira.mongodb.org/browse/DOCSP-9561
https://docs-mongodbcom-staging.corp.mongodb.com/befcf60/java/docsworker-xlarge/DOCSP-9561-CRUDCursor/fundamentals/crud/read-operations/cursor/
=> DOCSP-9561 crud cursor

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fundamentals/code-snippets/Retrieve.java
https://jira.mongodb.org/browse/DOCSP-15336
https://docs-mongodbcom-staging.corp.mongodb.com/59ad01c/java/docsworker-xlarge/DOCSP-15336-CRUDRetrieve/fundamentals/crud/read-operations/retrieve/
=> DOCSP-15336 crud retrieve

source/fundamentals/logging.txt, source/includes/fundamentals/logging.rst
Adds Fundamentals > Logging Page
https://jira.mongodb.org/browse/DOCSP-9572
https://docs-mongodbcom-staging.corp.mongodb.com/4949a9a/java/docsworker-xlarge/DOCSP-9572-Logging/fundamentals/logging/
=> Docsp 9572 logging

source/fundamentals/crud/write-operations/insert.txt, source/includes/fundamentals/code-snippets/Insert.java
https://jira.mongodb.org/browse/DOCSP-9566
https://docs-mongodbcom-staging.corp.mongodb.com/c55b1c8/java/docsworker-xlarge/DOCSP-9566-CRUDInsert/fundamentals/crud/write-operations/insert/
=> DOCSP-9566 crud insert

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/geo.txt, source/includes/fundamentals/code-snippets/Geo.java
Add the "Fundamentals > Crud > Read > Geospatial Queries" Page
https://jira.mongodb.org/browse/DOCSP-9562
https://docs-mongodbcom-staging.corp.mongodb.com/804492a/java/docsworker-xlarge/DOCSP-9562-Geo/fundamentals/crud/read-operations/geo/
NOTE: One of the links in this PR will not work until the PR is merged into master. I link to the Github source code for the examples in this PR, and as the file being linked is not present in the master branch the link doesn't work yet. Outside of this known error, all links should work as expected.
=> Docsp 9562 geospatial queries

source/faq.txt, source/index.txt
https://jira.mongodb.org/browse/DOCSP-2550
https://docs-mongodbcom-staging.corp.mongodb.com/0898c95/java/docsworker-xlarge/DOCSP-2550-FAQ/faq/
=> DOCSP-2550 FAQ page

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/project.txt
https://jira.mongodb.org/browse/DOCSP-9559
https://docs-mongodbcom-staging.corp.mongodb.com/353fa48/java/docsworker-xlarge/DOCSP-9559/fundamentals/crud/read-operations/project/
=> Docsp 9559

source/includes/quick-start/code-snippets/Movie.java, source/includes/quick-start/code-snippets/QuickStart.java, source/includes/quick-start/code-snippets/QuickStartPojoExample.java, source/includes/quick-start/gradle-versioned.rst, source/includes/quick-start/maven-versioned.rst, source/includes/quick-start/pojo-query-output.rst, source/includes/quick-start/query-output.rst, source/quick-start.txt
https://jira.mongodb.org/browse/DOCSP-12160
https://docs-mongodbcom-staging.corp.mongodb.com/954510d/java/docsworker-xlarge/DOCSP-12160-quickstart-pojos/quick-start/
=> DOCSP-12160: quickstart pojos

source/fundamentals/aggregation.txt
After looking around for suitable images, I couldn't find any that didn't require some sort of licensing agreement. Since there was no data that suggested the "illustrated example" section was useful, I've removed it.
https://jira.mongodb.org/browse/DOCSP-16528
https://docs-mongodbcom-staging.corp.mongodb.com/89d3f02/java/docsworker-xlarge/DOCSP-16528/fundamentals/aggregation/
=> remove gif and explanatory text

source/fundamentals/connection.txt, source/fundamentals/data-formats/documents.txt, source/fundamentals/data-formats/pojo-customization.txt, source/includes/language-compatibility-table-java.rst, source/usage-examples/count.txt
Fix Table Widths In Java Docs
https://jira.mongodb.org/browse/DOCSP-16490
https://docs-mongodbcom-staging.corp.mongodb.com/53abd97/java/docsworker-xlarge/DOCSP-16490-Tables/usage-examples/count/
https://docs-mongodbcom-staging.corp.mongodb.com/53abd97/java/docsworker-xlarge/DOCSP-16490-Tables/fundamentals/connection/
https://docs-mongodbcom-staging.corp.mongodb.com/53abd97/java/docsworker-xlarge/DOCSP-16490-Tables/fundamentals/data-formats/documents/
https://docs-mongodbcom-staging.corp.mongodb.com/53abd97/java/docsworker-xlarge/DOCSP-16490-Tables/fundamentals/data-formats/pojo-customization/
https://docs-mongodbcom-staging.corp.mongodb.com/53abd97/java/docsworker-xlarge/DOCSP-16490-Tables/compatibility/
=> Docsp 16490 tables

source/fundamentals/data-formats.txt
This PR removes the overview section that was on the page and adds a bulleted list of linked pages within the data formats section.
https://jira.mongodb.org/browse/DOCSP-17062
https://docs-mongodborg-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17062/
=> DOCSP-17062: Data Formats drawer

source/faq.txt
https://jira.mongodb.org/browse/DOCSP-17133
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17133-UpdateFAQ/faq/#do-i-have-to-specify-an-id-field-value-myself-
=> DOCSP-17133 update FAQ

source/faq.txt, source/fundamentals/auth.txt, source/fundamentals/connection.txt, source/fundamentals/data-formats/document-data-format-pojo.txt, source/fundamentals/monitoring.txt
Make an FAQ item to aggregate content related to `MongoClientSettings` and [add content covered in the github pages "Connect To MongoDB" page not covered in the upcoming java docs](http://mongodb.github.io/mongo-java-driver/4.3/driver/tutorials/connect-to-mongodb/). This includes:
- Connect to a replica set using `MongoClientSettings` with a seed list 
https://jira.mongodb.org/browse/DOCSP-16379
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-16379-MongoClientSettings/faq/
=> Docsp 16379 mongo client settings

source/api-documentation.txt, source/index.txt
Added drawer pages for the following API pages: Bson, Core, Sync
https://jira.mongodb.org/browse/DOCSP-17236
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17236-SeparateAPIDocLinks/
=> DOCSP-17236 drawer pages

source/fundamentals/builders/aggregates.txt
This updates the aggregation stages link to the correct location.
https://jira.mongodb.org/browse/DOCSP-17428
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17428/fundamentals/builders/aggregates/
=> Docsp 17428

config/redirects
Updated redirect url
https://jira.mongodb.org/browse/DOCSP-17486
=> Docsp 17486

source/whats-new.txt
Added information on What's New in 4.3.
Reference used: https://mongodb.github.io/mongo-java-driver/4.3/whats-new/ 
Also added bullets for the following java tickets:
- https://jira.mongodb.org/browse/JAVA-3927
- https://jira.mongodb.org/browse/JAVA-3866
- https://jira.mongodb.org/browse/JAVA-4203
https://jira.mongodb.org/browse/DOCSP-17218
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17218-WhatsNew4.3/whats-new/
=> DOCSP-17218 what's new in 4.3

source/faq.txt
Updated FAQ about discriminators to not have passive voice and to explain what a discriminator is.
https://jira.mongodb.org/browse/DOCSP-17445
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17445-FAQUpdate/faq/#what-is-a-discriminator-
=> DOCSP-17445 updated FAQ

snooty.toml
None
https://docs-mongodborg-staging.corp.mongodb.com/java/docsworker-xlarge/usage-example-landing-page/
=> Add usage examples to landing pages

source/faq.txt
Moved Issues and Help note to the bottom of the page.
N/A
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/FAQSections/faq/
=> FAQ Refactor

source/fundamentals.txt, source/index.txt
- Added mention of Versioned API and CSFLE in the fundamentals summary on the landing page.
- Added links to pages on the fundamentals drawer page.
https://jira.mongodb.org/browse/DOCSP-17579
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17579-FundamentalSummaryUpdate/
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17579-FundamentalSummaryUpdate/fundamentals/
=> DOCSP-17579 fundamentals section

source/fundamentals/connection/tls.txt
Rephrased a bullet and added note about TLS implementation.
https://jira.mongodb.org/browse/DOCSP-17244
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17244-TLSConfigProcedure/fundamentals/connection/tls/#configure-certificates
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17244-TLSConfigProcedure/fundamentals/connection/tls/#ocsp-stapling
=> DOCSP-17244 corrected TLS page phrasing

source/fundamentals/builders/aggregates.txt, source/fundamentals/builders/indexes.txt, source/fundamentals/builders/updates.txt, source/fundamentals/connection/tls.txt, source/fundamentals/crud/write-operations/bulk.txt, source/fundamentals/indexes.txt, source/fundamentals/versioned-api.txt
I went through each page and ran the broken link checker extension in chrome. In the files changed tab, you'll see exactly which links were changed for each page listed in staging. 
https://jira.mongodb.org/browse/DOCSP-17746
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17746-BrokenLinks/fundamentals/connection/tls/
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17746-BrokenLinks/fundamentals/versioned-api/
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17746-BrokenLinks/fundamentals/builders/aggregates/#setwindowfields
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17746-BrokenLinks/fundamentals/builders/indexes/ …
=> DOCSP-17746 fixed broken links

source/fundamentals/builders/projections.txt, source/fundamentals/crud/compound-operations.txt, source/fundamentals/crud/query-document.txt, source/fundamentals/crud/read-operations/project.txt, source/fundamentals/crud/write-operations/embedded-arrays.txt, source/usage-examples/count.txt, source/usage-examples/distinct.txt
Changed all occurrences of "query document" to "query filter".
https://jira.mongodb.org/browse/DOCSP-17660
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17660-QueryDocumentPhrase/
I'm not linking each and every page here because it's a word swap that can be seen in the files tab.
=> DOCSP-17660 query document phrase 

source/fundamentals/aggregation.txt, source/fundamentals/builders/aggregates.txt, source/fundamentals/builders/projections.txt, source/fundamentals/connection.txt, source/fundamentals/connection/jndi.txt, source/fundamentals/crud/compound-operations.txt, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/geo.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/read-operations/skip.txt, source/fundamentals/crud/read-operations/sort.txt, source/fundamentals/crud/read-operations/text.txt, source/fundamentals/crud/write-operations/bulk.txt, source/fundamentals/crud/write-operations/change-a-document.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/data-formats/documents.txt, source/fundamentals/data-formats/pojo-customization.txt, source/fundamentals/databases-collections.txt, source/fundamentals/enterprise-auth.txt, source/fundamentals/indexes.txt, source/fundamentals/logging.txt, source/fundamentals/monitoring.txt, source/includes/connect-guide-note.rst, source/includes/legacy-redirect.rst, source/includes/quick-start/jdk-tls-issue.rst, source/quick-start.txt, source/usage-examples/bulkWrite.txt, source/usage-examples/command.txt
Updated callout types that seemed incorrect.
Reference used to determine the changes: https://docs.mongodb.com/meta/style-guide/style/callouts/ 
https://jira.mongodb.org/browse/DOCSP-17661
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17661-CalloutTypeEdits/
Refer to the files tab to see the changes made.
=> DOCSP-17661 callout types

source/fundamentals/crud/read-operations/cursor.txt
https://jira.mongodb.org/browse/DOCSP-17642
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17642-Cursor-Definition/fundamentals/crud/read-operations/cursor/
=> DOCSP-17642 add cursor definition

source/fundamentals/connection.txt, source/fundamentals/connection/tls.txt, source/fundamentals/indexes.txt, source/includes/fundamentals/localhost-connection.rst, source/includes/localhost-connection.rst, source/includes/quick-start/atlas-setup.rst, source/quick-start.txt, source/usage-examples.txt, source/whats-new.txt
https://jira.mongodb.org/browse/DOCSP-17791
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17791-new-local-instructions/fundamentals/connection/
[Quickstart](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17791-new-local-instructions/quick-start/)
[Connection Guide](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17791-new-local-instructions/fundamentals/connection/#connect-to-a-mongodb-server-on-your-local-machine)
[Build log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=611151467dcf01293019ac3c)
=> DOCSP-17791: new local MongoDB connection instructions

snooty.toml, source/includes/quick-start/gradle-versioned.rst, source/includes/quick-start/maven-versioned.rst
This adds a minor version constant and uses it in the quickstart files.
https://jira.mongodb.org/browse/DOCSP-18536
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61382c127dcf012930a1a4ba
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-18536/quick-start/
=> update minor version

source/fundamentals/auth.txt, source/includes/fundamentals/code-snippets/auth-credentials-aws.rst
Information on refreshing credentials with the MONGODB-AWS authMechanism.
Note. This is the same PR as #170 but with the correct branch name.
https://jira.mongodb.org/browse/DOCSP-18856
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=617adc85c13055282d7dbb3e
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-18856/fundamentals/auth/#refresh-credentials
=> aws credential refreshing

snooty.toml
Updates displayed version to 4.3.4.
🔥  Needs cherry-pick to 4.3 branch. 🔥 
https://jira.mongodb.org/browse/DOCSP-19346
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6182932ac13055282d48162e
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-19436/quick-start/#add-mongodb-as-a-dependency
=> updates patch version

source/fundamentals/monitoring.txt
Add information about how to incorporate MongoDB Java Driver event information into distributed tracing systems.
https://jira.mongodb.org/browse/DOCSP-18851
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61859e5ec13055282d1b940e
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-18851-Distribute-Trace/fundamentals/monitoring/#construct-distributed-traces
=> (DOCSP-18851) Include Driver Data In Distributed Tracing System

source/index.txt
https://jira.mongodb.org/browse/DOCSP-19159
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6197f67f5314b0809ff49ea4
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-19159-landing-page-updates/#introduction
=> DOCSP-19159: landing page updates

source/fundamentals/connection.txt
Clarify optional dependencies for compression.
https://jira.mongodb.org/browse/DOCSP-19854
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=619e83015314b0809f6f789d
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-19854/fundamentals/connection/#compression-algorithm-dependencies
=> Docsp 19854

snooty.toml
https://jira.mongodb.org/browse/DOCSP-20251
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61dc614f41accb3633b53853
https://docs-mongodborg-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-20251/
=> update to 4.4.1

source/fundamentals/connection/connection-options.txt, source/includes/mongodb-compatibility-table-java.rst
Add srvServiceName option.
https://jira.mongodb.org/browse/DOCSP-20131
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61e1a08cbcf82347e5b29eaa
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-20131-srvServiceName/fundamentals/connection/connection-options/#connection-options
=> (DOCSP-20131) srvServiceName

source/index.txt
https://jira.mongodb.org/browse/DOCSP-20496
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61f022fcbcf82347e5c59c7c
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-20496/
=> (DOCSP-20496) standardize driver intros: java

source/index.txt
* (DOCSP-20496) standardize driver intros: java
https://jira.mongodb.org/browse/DOCSP-20535
**Paste your workerpool job link here**
https://docs-mongodborg-staging.corp.mongodb.com/java/docsworker-xlarge/NNNNNNNNNNN/
=> (DOCSP-20496) standardize driver intros: java (#198)

config/redirects, snooty.toml, source/fundamentals.txt, source/fundamentals/connection/mongoclientsettings.txt, source/fundamentals/stable-api.txt, source/includes/fundamentals-sections.rst, source/includes/fundamentals/code-snippets/StableApiExample.java, source/whats-new.txt
https://jira.mongodb.org/browse/DOCSP-20585
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61f43fb9382d7fe4ee37b77e
[ToC](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-20585-stable-api/#fundamentals
)
[What's New](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-20585-stable-api/whats-new/#what-s-new-in-4.3)
[Fundamentals ToC](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-20585-stable-api/fundamentals/)
[Stable API](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-20585-stable-api/fundamentals/stable-api/) (linked Server Manual page not published yet)
=> DOCSP-20585: versioned API renamed to stable API

snooty.toml
https://jira.mongodb.org/browse/DOCSP-20733
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6202e310382d7fe4ee3760fc
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-20733-update-version/quick-start/#add-mongodb-as-a-dependency
=> DOCSP-20733: update version to 4.4.2

source/whats-new.txt
https://jira.mongodb.org/browse/DOCSP-20939
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=620d7c189c4c7f6bfb1099de
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-20939-whats-new-4.5/whats-new/#what-s-new-in-4.5
=> DOCSP-20939: what's new updates for 4.5

source/fundamentals/connection.txt, source/includes/connect-guide-note.rst
None
**Paste your workerpool job link here**
https://docs-mongodborg-staging.corp.mongodb.com/java/docsworker-xlarge/NNNNNNNNNNN/
=> fix link syntax

source/fundamentals/csfle.txt
Fix CSFLE collection name.
https://jira.mongodb.org/browse/DOCSP-21585
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=623e12350ab54725f12c17e0
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-21585-Fix-CSFLE-Coll/fundamentals/csfle/#automatic-encryption-and-decryption
=> (DOCSP-21585) Fix Key Vault Namespace

.github/pull_request_template.md, README.rst
This removes mention of MongoDB internal resources.
https://jira.mongodb.org/browse/DOCSP-22060
=> no private company references

source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/crud/read-operations/project.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/read-operations/skip.txt, source/fundamentals/crud/read-operations/sort.txt, source/fundamentals/crud/read-operations/text.txt, source/fundamentals/crud/write-operations/bulk.txt, source/fundamentals/crud/write-operations/change-a-document.txt, source/fundamentals/crud/write-operations/delete.txt, source/fundamentals/crud/write-operations/embedded-arrays.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/indexes.txt, source/includes/quick-reference/QuickReferenceSnippets.java, source/index.txt, source/quick-reference.txt, source/usage-examples/bulkWrite.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/distinct.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt, source/usage-examples/watch.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-21520
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-21520-java-quick-reference/quick-reference/
=> DOCSP-21520: quick reference page

source/fundamentals/connection/mongoclientsettings.txt, source/fundamentals/logging.txt
Admonition to Log Connection Settings.
JIRA - https://jira.mongodb.org/browse/DOCSP-23102
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-23102-Log-Connection-Settings/fundamentals/connection/mongoclientsettings/#example
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=629e23f87cf53975253e3024)
=> (DOCSP-23102) Log Connection Settings

source/usage-examples/count.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-22465
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-22465-count-command/usage-examples/count/
=> DOCSP-22465: admonition on stable API and estimatedDocumentCount method

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-23104
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-23104-driver-4.7.0-beta0/quick-start/#add-mongodb-as-a-dependency
Maven Central Repo (for version verification):
https://search.maven.org/artifact/org.mongodb/mongodb-driver-sync/4.7.0-beta0/jar
=> DOCSP-23104: Driver 4.7.0-beta0 release

source/fundamentals/builders/indexes.txt, source/includes/quick-start/create-project.rst, source/upgrade.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-23279
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-23279-fix-typo/upgrade/
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-23279-fix-typo/quick-start/
=> Docsp 23279 fix typo

source/includes/quick-start/create-project.rst, source/upgrade.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-23279
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/
=> DOCSP-23279: fixed two typos

source/fundamentals/indexes.txt
Added a section on the Indexes page on how to specify a clustered index.
JIRA - https://jira.mongodb.org/browse/DOCSP-22866
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-22866/fundamentals/indexes/#clustered-indexes
=> DOCSP-22866 clustered indexes

config/redirects, snooty.toml, source/fundamentals/indexes.txt, source/whats-new.txt
JIRA - N/A
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/4.7-release/whats-new/
=> 4.7 release

source/upgrade.txt
Fix for  https://github.com/mongodb/docs-java/pull/245
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/
=> fix link to API doc

snooty.toml, source/whats-new.txt
Cherry picks squashed commit from [this pull request](https://github.com/mongodb/docs-java/pull/250#pullrequestreview-1065199302).
JIRA - https://jira.mongodb.org/browse/DOCSP-24130
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/v4.7/whats-new/
Build - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62f112bc230aeb802e598364
=> (DOCSP-24130) libmongocrypt patch

source/fundamentals/data-formats/pojo-customization.txt, source/includes/fundamentals/code-snippets/bson-extra-elements/BsonExtraElementsExample.java, source/includes/fundamentals/code-snippets/bson-extra-elements/ProductWithBsonExtraElements.java
JIRA - https://jira.mongodb.org/browse/DOCSP-23027
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-23027-bsonextraelements-example/fundamentals/data-formats/pojo-customization/
=> DOCSP-23027: BsonExtraElements Annotation

source/upgrade.txt
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/080222-typo-fix/upgrade/#version-4.0-breaking-changes
=> Fix typo on upgrade page

source/fundamentals/data-formats/pojo-customization.txt, source/includes/fundamentals/code-snippets/bson-extra-elements/BsonExtraElementsExample.java, source/includes/fundamentals/code-snippets/bson-extra-elements/ProductWithBsonExtraElements.java, source/upgrade.txt
https://github.com/mongodb/docs-java/pull/249
https://github.com/mongodb/docs-java/pull/242
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62f128ff230aeb802e5df691
=> Backport BsonExtraElements and typo fix

source/upgrade.txt
(cherry picked from commit 9830df3ff0dcf0e3560b4a93e0036447e7c3b610)
https://github.com/mongodb/docs-java/pull/249
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62f12956230aeb802e5e2e92
=> Backport: typo fix

source/fundamentals/builders/aggregates.txt, source/includes/fundamentals/code-snippets/builders/AggregateSearchBuilderExample.java, source/includes/fundamentals/code-snippets/builders/BuildersIntro.java
JIRA - https://jira.mongodb.org/browse/DOCSP-21671
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-21671-atlas-search-builder/fundamentals/builders/aggregates/#atlas-full-text-search
=> DOCSP-21671: Atlas Text Search Builder

source/fundamentals/builders/aggregates.txt, source/includes/fundamentals/code-snippets/builders/AggregateSearchBuilderExample.java
JIRA - https://jira.mongodb.org/browse/DOCSP-22127
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-22127-atlas-searchmeta-builder/fundamentals/builders/aggregates/#atlas-search-metadata
=> DOCSP-22127: Atlas searchMeta builder

source/fundamentals/builders/aggregates.txt, source/includes/fundamentals/code-snippets/builders/AggregateSearchBuilderExample.java, source/includes/fundamentals/code-snippets/builders/BuildersIntro.java
Cherry-picked changes for:
https://github.com/mongodb/docs-java/pull/258
https://github.com/mongodb/docs-java/pull/259
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/v4.7/fundamentals/builders/aggregates/#atlas-full-text-search
=> DOCSP-21671 and DOCSP-22127: Add Atlas Text Search and searchMeta builders

source/fundamentals/builders/aggregates.txt
(cherry picked from commit 967ae136f6cd2f3c108500616e4c1e4e9fedad0f)
Backport of https://github.com/mongodb/docs-java/pull/261
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/v4.7/fundamentals/builders/aggregates/#setwindowfields
=> 081622: update builder link and link description (#261)

.github/workflows/copy-compat-to-docs-shared.yml
Add option to trigger copy to docs-shared manually instead of on PR
=> allow copy workflow to trigger manually

source/compatibility.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/add-manual-workflow/compatibility/
Build - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62fe75f0b354ebcf055c54cb
=> Point to compat tables in docs-shared

source/compatibility.txt
(cherry picked from commit deeef61d483bb89ba780eb3d4182fcb6a2886b13)
Staging - https://docs-mongodborg-staging.corp.mongodb.com/java/docsworker-xlarge/v4.6/
Build - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62fe9b50b354ebcf0562bada
=> point to compat tables in docs-shared [v4.6 backport]

source/compatibility.txt
(cherry picked from commit deeef61d483bb89ba780eb3d4182fcb6a2886b13)
Staging - https://docs-mongodborg-staging.corp.mongodb.com/java/docsworker-xlarge/v4.5/
Build - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62fe9bb9b354ebcf0562ca2c
=> point to compat tables in docs-shared [v4.5 backport]

source/compatibility.txt
(cherry picked from commit deeef61d483bb89ba780eb3d4182fcb6a2886b13)
Staging - https://docs-mongodborg-staging.corp.mongodb.com/java/docsworker-xlarge/v4.4/
Build - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62fe9eb5b354ebcf0563952d
=> point to compat tables in docs-shared [v4.4 backport]

source/compatibility.txt
(cherry picked from commit deeef61d483bb89ba780eb3d4182fcb6a2886b13)
Staging - https://docs-mongodborg-staging.corp.mongodb.com/java/docsworker-xlarge/v4.3/
Build - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62fe9eadb354ebcf056393b3
=> point to compat tables in docs-shared [v4.3 backport]

source/fundamentals/builders/aggregates.txt, source/includes/fundamentals/code-snippets/builders/AccumulatorsPickN.java
JIRA - https://jira.mongodb.org/browse/DOCSP-22988
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-22988-pick-n-accumulators/fundamentals/builders/aggregates/#pick-n-accumulators
=> DOCSP-22988: pick n accumulators

source/fundamentals/builders/aggregates.txt, source/includes/fundamentals/code-snippets/builders/AccumulatorsPickN.java
* DOCSP-22988: pick n accumulators
(cherry picked from commit 010cf98818b1790434ed647357c00366b506597a)
JIRA - https://jira.mongodb.org/browse/DOCSP-22988
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/v4.7/fundamentals/builders/aggregates/
=> DOCSP-22988: pick n accumulators (#270)

source/fundamentals/builders/aggregates.txt, source/includes/fundamentals/code-snippets/builders/AccumulatorsPickN.java, source/includes/fundamentals/code-snippets/builders/AggregateDensify.java, source/whats-new.txt
Link checker false positive on mongo-crypt link, not relevant to this PR.
JIRA - https://jira.mongodb.org/browse/DOCSP-23138
Staging - 
[What's New](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-23138-aggregates-densification/whats-new/#what-s-new-in-4.7)
[Densify Builder](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-23138-aggregates-densification/fundamentals/builders/aggregates/#densify)
=> DOCSP-23138: Densify Aggregates Builder

source/fundamentals/builders/aggregates.txt, source/includes/fundamentals/code-snippets/builders/AccumulatorsPickN.java, source/includes/fundamentals/code-snippets/builders/AggregateDensify.java, source/whats-new.txt
* DOCSP-23138: Densify Aggregates Builder
(cherry picked from commit fff655231e3efb0f2414460d7bd371588f7b2df6)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/v4.7/fundamentals/builders/aggregates/#densify
=> DOCSP-23138: Densify Aggregates Builder (#272)

source/fundamentals/data-formats.txt, source/fundamentals/data-formats/codecs.txt, source/fundamentals/data-formats/document-data-format-pojo.txt, source/fundamentals/data-formats/document-data-format-record.txt, source/fundamentals/data-formats/pojo-customization.txt, source/includes/fundamentals/code-snippets/records/CodecRecordExample.java, source/includes/fundamentals/code-snippets/records/DataStorageRecord.java, source/whats-new.txt
* DOCSP-22293: Records and Codec Provider
(cherry picked from commit 444d6bc4b2488ccb8998e09d42e5dbf9680af620)
JIRA - https://jira.mongodb.org/browse/DOCSP-NNNNN
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/
=> DOCSP-22293: Records and Codec Provider (#280)

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-23724
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-23724-mongodb-3.4-support-upcoming/whats-new/#upcoming-breaking-changes
=> DOCSP-23724: announce MongoDB server support breaking change

source/fundamentals/data-formats/document-data-format-record.txt, source/includes/fundamentals/code-snippets/records/NetworkDeviceRecord.java, source/includes/fundamentals/code-snippets/records/RecordAnnotationExample.java
JIRA - https://jira.mongodb.org/browse/DOCSP-22977
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-22977-record-annotations/fundamentals/data-formats/document-data-format-record/#specify-field-conversion-using-annotations
Given the similarities of the Records Page and the [POJOs page](https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/data-formats/document-data-format-pojo/), I plan to ticket future work to determine the best way to organize the information to reduce duplication. This page doesn't contain as much detail as the POJOs page, but directs to other pages that should help the reader locate the omitted info.
=> DOCSP-22977: Java record annotations

source/fundamentals/data-formats/document-data-format-extended-json.txt
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/100522-link-fix/fundamentals/data-formats/document-data-format-extended-json/
=> remove outdated link

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-25868
Staging:
- [Quick Start driver install](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-25868-4.8.0-beta0/quick-start/#add-mongodb-as-a-dependency)
- [BSON install](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-25868-4.8.0-beta0/fundamentals/data-formats/document-data-format-bson/#install-the-bson-library)
- Also check the API documentation links (no landing page) from the left nav
=> DOCSP-25868: Updates for v4.8.0-beta0

source/fundamentals/monitoring.txt, source/usage-examples/command.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26237
Staging - 
- [Run a command](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/Docsp-26237/usage-examples/command/)
- [Monitoring](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/Docsp-26237/fundamentals/monitoring/)
=> DOCSP-26237 Fixed broken links

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-26245
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-26245-mongodb-crypt-version/fundamentals/csfle/#mongodb-crypt
=> DOCSP-26245 update mongocrypt version

source/fundamentals/data-formats/document-data-format-record.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-25900
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-25900-recursive-type-support/fundamentals/data-formats/document-data-format-record/#operations-with-recursive-types
=> DOCSP-25900: recursive type support

source/upgrade.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-25464
Staging:
[What's New](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-25464-recordcodec-support/whats-new/#std-label-version-4.8)
[Upgrade driver verions](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-25464-recordcodec-support/upgrade/#version-4.8-breaking-changes)
=> DOCSP-25464: RecordCodec changes in v4.8

source/fundamentals/auth.txt, source/includes/fundamentals/code-snippets/MongoDbAwsAuth.java
Restructured page to accommodate AWS SDK as a method for performing MONGODB-AWS authentication and separate each method into a more coherent example.
JIRA - https://jira.mongodb.org/browse/DOCSP-25962
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-25962-aws-sdk/fundamentals/auth/#std-label-mongodb-aws-auth-mechanism
=> DOCSP-25962: MONGODB-AWS aws sdk info

source/index.txt
This PR corrects the Java driver index page. The Jira ticket specifically mentions the Java landing page, which is corrected in [another PR. ](https://github.com/mongodb/docs-ecosystem/pull/849)
JIRA - https://jira.mongodb.org/browse/DOCS-15757
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/docs-15757-mdbu-link/
=> [DOCS-15757] MDBU link update

source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-25436
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-25436/
=> DOCSP-25436 Added a note about asynchronous Java drivers.

source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-25436
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-25436/
=> DOCSP-25436 Added a note about asynchronous Java drivers. (#302)

source/includes/quick-start/code-snippets/QuickStart.java, source/quick-start.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26555
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-26555-quickstart-update/quick-start/#query-your-mongodb-cluster-from-your-application
=> DOCSP-26555: update quickstart

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/change-streams.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fundamentals/code-snippets/change-streams/ChangeStreams.java, source/includes/fundamentals/code-snippets/change-streams/ConfiguredChangeStream.java
JIRA - https://jira.mongodb.org/browse/DOCSP-22297
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-22297-change-streams-pre-post/fundamentals/crud/read-operations/change-streams/
=> DOCSP-22297: change streams, pre and post images

source/fundamentals/auth.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/auth-typos/fundamentals/auth/#mongodb-aws
=> Authentication page typo fixes

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-27409
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-27409-4.8.2-update/quick-start/#add-mongodb-as-a-dependency
=> DOCSP-27409: 4.8.2 patch release

source/upgrade.txt
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/012422-fix-source-constant/upgrade/
=> fix source constant

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-25999
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-25999/whats-new/#std-label-version-4.8
=> DOCSP-25999: Added note about new Codec classes.

source/fundamentals/connection.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27932
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-27932-add-aws-lambda-link/fundamentals/connection/
=> DOCSP-27932: add AWS Lambda connection guide link

source/fundamentals/data-formats/pojo-customization.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27400
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-27400-bsoncreator-update/fundamentals/data-formats/pojo-customization/#annotations
=> DOCSP-27400: BsonCreator annotation description fix

source/api-documentation.txt, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-25493 (in part - this is the portion that will be backported as it just points to the bson-record API).
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-25493/
=> DOCSP-25493: Adding links to the bson-records API

source/fundamentals/logging.txt, source/includes/fundamentals/logging.rst, source/whats-new.txt
JIRA:
- https://jira.mongodb.org/browse/DOCSP-27978
- https://jira.mongodb.org/browse/DOCSP-27417
Staging:
- [What's New v4.9
](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/java-4.9-whats-new/whats-new/#what-s-new-in-4.9)
- [Logging](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/java-4.9-whats-new/fundamentals/logging/#example---set-up)
=> Java 4.9 whats new

source/compatibility.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/v4.9/compatibility/
=> compat updates

source/fundamentals/builders/aggregates.txt, source/includes/fundamentals/code-snippets/builders/AggBuilders.java
JIRA - https://jira.mongodb.org/browse/DOCSP-28226
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-28226-incorrect-code-snippet/fundamentals/builders/aggregates/#sample
=> DOCSP-28226 Fix incorrect sample() code snippet

source/fundamentals/data-formats/document-data-format-record.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-25493
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-25493-record-codec-topic/fundamentals/data-formats/document-data-format-record/#fundamentals-records-get-codec
=> Docsp 25493 record codec topic

source/fundamentals/builders/aggregates.txt, source/includes/fundamentals/code-snippets/builders/AggBuilders.java, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27977
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/docsp-27977-documents-stage/fundamentals/builders/aggregates/
=> Docsp 27977 - documents stage

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24790
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-24790-disambiguatedpaths/whats-new/#what-s-new-in-4.8
=> DOCSP-24790: Add info on disambiguatedPaths change stream event field

source/fundamentals/builders/aggregates.txt, source/fundamentals/builders/projections.txt, source/fundamentals/databases-collections.txt
JIRA - None
Staging - 
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/030223-fix-typos-terminology/fundamentals/builders/aggregates/#replaceroot
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/030223-fix-typos-terminology/fundamentals/builders/projections/#project-an-array-slice
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/030223-fix-typos-terminology/fundamentals/databases-collections/#specify-read-preferences--read-concerns--and--write-concerns
=> Fix typos and terminology issues

source/fundamentals/connection/connect.txt, source/includes/fundamentals/code-snippets/srv.java
JIRA - https://jira.mongodb.org/browse/DOCSP-27922
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-27922-connection-updates-atlas/fundamentals/connection/connect/#atlas-connection-example
=> DOCSP-27922: connection updates atlas

source/fundamentals/aggregation/aggregation-expression-operations.txt, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28586
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/how-to-use-section/fundamentals/aggregation/aggregation-expression-operations/#how-to-use-operations
=> DOCSP-28586: How to use section

source/fundamentals/aggregation/aggregation-expression-operations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28010
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-28010-string-ops/fundamentals/aggregation/aggregation-expression-operations/#string-operations
=> DOCSP-28010: string operations

source/includes/fundamentals/code-snippets/srv.java
JIRA - [DOCSP-27922](https://jira.mongodb.org/browse/DOCSP-27922)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/stable-api-updates-cleanup/fundamentals/connection/connect/#atlas-connection-example
=> match convention

source/usage-examples/count.txt
This will backport the following commits from `master` to `v4.9`:
=> [v4.9] DOCSP-27256 Add note for collScan workaround (#350)

source/usage-examples/count.txt
This will backport the following commits from `master` to `v4.6`:
=> [v4.6] DOCSP-27256 Add note for collScan workaround (#350)

source/usage-examples/count.txt
This will backport the following commits from `master` to `v4.5`:
=> [v4.5] DOCSP-27256 Add note for collScan workaround (#350)

source/usage-examples/count.txt
This will backport the following commits from `master` to `v4.3`:
=> [v4.3] DOCSP-27256 Add note for collScan workaround (#350)

source/usage-examples/count.txt
This will backport the following commits from `master` to `v4.7`:
=> [v4.7] DOCSP-27256 Add note for collScan workaround (#350)

source/usage-examples/count.txt
This will backport the following commits from `master` to `v4.4`:
=> [v4.4] DOCSP-27256 Add note for collScan workaround (#350)

source/fundamentals/aggregation/aggregation-expression-operations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28007
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-28007-date-ops/fundamentals/aggregation/aggregation-expression-operations/#date-operations
=> DOCSP-28007: date operations

source/fundamentals/aggregation/aggregation-expression-operations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28002
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-28002-arithmetic-operations/fundamentals/aggregation/aggregation-expression-operations/#arithmetic-operations
=> Docsp 28002 arithmetic operations

source/fundamentals/aggregation/aggregation-expression-operations.txt, source/fundamentals/data-formats/documents.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28003
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-28003-array-ops/fundamentals/aggregation/aggregation-expression-operations/#array-operations
=> DOCSP-28003: Array Operations

source/faq.txt, source/fundamentals/connection/connect.txt, source/fundamentals/databases-collections.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28556
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-28556-reuse-client/faq/#how-does-connection-pooling-work-in-the-java-driver-)
=> DOCSP-28556: connection pool + reuse client

source/fundamentals/aggregation/aggregation-expression-operations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28005
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-28005-comparison-operations/fundamentals/aggregation/aggregation-expression-operations/#comparison-operations
=> DOCSP-28005: Adding comparison agg operators

source/fundamentals/aggregation/aggregation-expression-operations.txt, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28808
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-28808-conversion-operations/fundamentals/aggregation/aggregation-expression-operations/#conversion-operations)
=> DOCSP-28808: conversion operations

source/fundamentals/aggregation/aggregation-expression-operations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28864
[**Staging**](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-28864-passTo-operations/fundamentals/aggregation/aggregation-expression-operations/#function-operations)
=> DOCSP-28864: function (passTo) operations

source/fundamentals/aggregation/aggregation-expression-operations.txt
JIRA -
- https://jira.mongodb.org/browse/DOCSP-28006
- https://jira.mongodb.org/browse/DOCSP-28009
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-28006-conditional-operations/fundamentals/aggregation/aggregation-expression-operations/#conditional-expression-operations
=> DOCSP-28006: Added conditional and set operations

snooty.toml
Updating full Java version to 4.9.1
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/Java-491-release/quick-reference/) (scroll down to bottom to see version)
=> update to new patch version

source/api-documentation.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29114
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-29114-api-documentation-summary/api-documentation/
=> DOCSP-29114: API documentation summary

source/includes/fundamentals/code-snippets/Delete.java
JIRA - https://jira.mongodb.org/browse/DOCSP-29298
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/docsp-29298-fix-delete/fundamentals/crud/write-operations/delete/
=> docsp-29298 - fix example

source/quick-reference.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-22622 
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/master/quick-reference/
=> DOCSP-22622 Changed default visibility for code blocs so they are hidden

.backportrc.json
Enables running the backport command.
JIRA - None
Staging - None
=> Add backportrc file

snooty.toml, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29311
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/docsp-29311-breaking-changes/whats-new/
- [] Are all the links working?
=> docsp-29311 - upcoming breaking changes

source/fundamentals/connection/mongoclientsettings.txt, source/includes/fundamentals/code-snippets/mcs.java
JIRA - https://jira.mongodb.org/browse/DOCSP-27636
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-27636/fundamentals/connection/mongoclientsettings/#logger-settings
=> Docsp 27636: Add maxDocumentLength

source/fundamentals/aggregation-expression-operations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29469
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-29469-fix-links/fundamentals/aggregation-expression-operations/#document-operations
=> DOCSP-29469: Fix links on Aggregation Expression Operators page

source/faq.txt, source/fundamentals/builders.txt, source/fundamentals/builders/aggregates.txt, source/fundamentals/connection/mongoclientsettings.txt, source/fundamentals/crud/read-operations/geo.txt, source/fundamentals/data-formats/codecs.txt, source/fundamentals/data-formats/document-data-format-pojo.txt, source/fundamentals/databases-collections.txt, source/fundamentals/indexes.txt, source/includes/quick-start/atlas-setup.rst, source/usage-examples.txt, source/usage-examples/deleteMany.txt, source/whats-new.txt
JIRA - No Jira ticket
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/Typo-fixes/
=> Minor typo and style guide fixes

snooty.toml
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/Snooty-fix/
Build - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=644ad4927efd2382b3154c29
=> Removed duplicate snooty entry.

source/faq.txt, source/fundamentals/builders.txt, source/fundamentals/builders/aggregates.txt, source/fundamentals/connection/mongoclientsettings.txt, source/fundamentals/crud/read-operations/geo.txt, source/fundamentals/data-formats/codecs.txt, source/fundamentals/data-formats/document-data-format-pojo.txt, source/fundamentals/databases-collections.txt, source/fundamentals/indexes.txt, source/includes/quick-start/atlas-setup.rst, source/usage-examples.txt, source/usage-examples/deleteMany.txt, source/whats-new.txt
Changes already reviewed - creating this PR since backporting generated auto-merge warnings.
=> Minor typo and style guide fixes (#377)

snooty.toml, source/fundamentals/crud/read-operations/limit.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29523
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-29523-fix-skip-and-limit-example/fundamentals/crud/read-operations/limit/
=> DOCSP-29523: fix skip and limit example

source/fundamentals/crud/compound-operations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29537
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-29537-fix-findandreplace-output/fundamentals/crud/compound-operations/#find-and-update
=> DOCSP-29537: fix findAndReplace example output

source/index.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29626
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-29626-move-WN/#what-s-new and see left nav
=> DOCSP-29626: move whats new in nav and new anchor

snooty.toml, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29688
Staging: 
- https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-29688-add-missing-source-constant/upgrade/#overview
- https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-29688-add-missing-source-constant/fundamentals/crud/read-operations/change-streams/
=> DOCSP-29688: add missing source constant

source/faq.txt
JIRA - none, while doing work on Connection Troubleshooting Guide for other languages, I realized some duplicate info was left and no link was added to the FAQ. This PR fixes that oversight.
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/050923-remove-duplicate-info/faq/
=> Removed duplicate info and added a link to Connection guide

source/connection-troubleshooting.txt, source/index.txt
JIRA - No ticket
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/Add-missing-CGL-description/#connection-troubleshooting
=> Added the connection troubleshooting description to index

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-30261
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-30261-fix-link/whats-new/#std-label-version-4.3
=> DOCSP-30261: fix link to Atlas Serverless product

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-30783
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-30783-sealed-annotation/whats-new/#what-s-new-in-4.10
=> DOCSP-30783: certain interfaces are sealed in v4.10

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29280
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-29280-no-duplicate-log-msg/whats-new/#what-s-new-in-4.10)
=> DOCSP-29280: no more duplicate retry log msgs

source/faq.txt, source/fundamentals/builders.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26369
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-26369-faq-invalid-bson-field-name/faq/#how-do-i-prevent-the--illegalargumentexception--invalid-bson-field-name--error-
=> DOCSP-26369: FAQ entry for invalid bson field name

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-30854
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/v4.3-EOL/
=> DOCSP-30854: Java docs - EOL v4.3

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-30854
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/v4.4-EOL/
=> DOCSP-30854: Java docs - EOL v4.4

source/fundamentals/monitoring.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-32036
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-32036-monitoring-link-fix/fundamentals/monitoring/#server-discovery-and-monitoring-events) (link at bottom of section)
- [] Did you run a spell-check?
- [] Did you run a grammar-check?
=> DOCSP-32036: fix link on monitoring page

source/fundamentals/aggregation-expression-operations.txt
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/081623-broken-links/fundamentals/aggregation-expression-operations/#array-operations
=> Fix broken links

source/facets.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-32483
Hey @mongoKart - here's the facet.toml file for the java sync driver repo.  Please merge if everything looks good!
Thanks!
Sarah
=> DOCSP-32483 programmatic tagging script for java sync repo

source/compatibility.txt, source/includes/quick-start/atlas-setup.rst, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-33169
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-33169-quick-start-version-num/quick-start/
=> DOCSP-33169: Quick Start version number

source/compatibility.txt, source/includes/lifecycle-schedule-callout.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-30911
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/java/DOCSP-30911-server-support/compatibility/#mongodb-compatibility
=> DOCSP-30911: Add lifecycle server support callout

source/includes/fact-environments.rst, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-32300
Staging - https://docs-mongodborg-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-32300/
Build - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6512fd66492df295cff4a9c5
=> DOCSP-32300 Adds compatibility info to landing page

source/includes/fact-environments.rst, source/index.txt
(cherry picked from commit 2b26b204a51ba57b52b1b12ba4f052e04fa1bafa)
Backporting #449 
JIRA - https://jira.mongodb.org/browse/DOCSP-32300
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-32297v45/
=> DOCSP-32300 Adds compatibility info to landing page (#449)

config/redirects, source/fundamentals/aggregation-expression-operations.txt, source/fundamentals/connection.txt, source/fundamentals/connection/connection-options.txt, source/fundamentals/connection/jndi.txt, source/fundamentals/connection/socks.txt, source/fundamentals/crud/read-operations/change-streams.txt, source/fundamentals/data-formats/document-data-format-extended-json.txt, source/includes/fact-environments.rst, source/index.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-32942
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-32942-deprecated-methods/whats-new/#what-s-new-in-4.11
=> DOCSP-32942: Deprecated Methods

source/compatibility.txt
Followup task to v4.11 release.
JIRA - None
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/java/v4.11-compat-sharedincludes/compatibility/
=> 101023: shared include compatibility tables

source/index.txt, source/quick-start.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34415>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-34415-improve-index/#introduction
=> DOCSP-34415: improve index

source/usage-examples/facets.toml
Hey @ccho-mongodb - here's the additional facets.toml file for the java usage examples.
JIRA - <https://jira.mongodb.org/browse/DOCSP-31343>
Staging - <https://preview-mongodbsarahemlin.gatsbyjs.io/java/DOCSP-31343/>
=> DOCSP-31343 additional facets.toml file

source/fundamentals/data-formats/document-data-format-record.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34104>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-34104/fundamentals/data-formats/document-data-format-record/#specify-component-conversion-using-annotations>
=> [JAVA] Remove deprecated record annotations

source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34502>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-34502-clusterconnectionmode/whats-new/#what-s-new-in-5.0
=> DOCSP-34502: consistent computation of connection mode

source/upgrade.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-35082>
Staging
- <https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-35082/upgrade/#std-label-java-breaking-changes-v5.0>
- <https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-35082/whats-new/#std-label-version-5.0>
****** see note
=> [JAVA] Improve map/flatmap of Publisher[Void]

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-35626>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/v4.5/
=> DOCSP-35626: eol v4.5

source/whats-new.txt
This PR addresses an extra request added to the DOCSP-35011 ticket.
JIRA - <https://jira.mongodb.org/browse/DOCSP-35011>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-35011-whats-new-link/whats-new/>
=> DOCSP-35011: Add ConnectionId changes link to What's New

source/fundamentals/connection/tls.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36306>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/java/DOCSP-36306-openssl-link-fix/fundamentals/connection/tls/#configure-the-jvm-key-store
=> DOCSP-36306: OpenSSL link fix

source/upgrade.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34456>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-34456/upgrade/#version-5.0-breaking-changes>
=> [JAVA] Remove deprecated event-related classes

source/fundamentals/connection/mongoclientsettings.txt, source/fundamentals/connection/socks.txt, source/fundamentals/connection/tls.txt, source/upgrade.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33650>
Staging
- [Breaking Changes](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-33650/upgrade/#breaking-changes)
- [Specify MongoClient Settings](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-33650/fundamentals/connection/mongoclientsettings/)
- [Connect to MongoDB by Using a SOCKS5 Proxy](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-33650/fundamentals/connection/socks/)
- [Customize TLS/SSL Configuration through the Netty SslContext](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-33650/fundamentals/connection/tls/#customize-tls- …
=> [JAVA] Remove deprecated Stream-related types

source/fundamentals/crud/read-operations/cursor.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-38266>
Staging - <https://preview-mongodbjwilliamsmongo.gatsbyjs.io/java/DOCSP-38266/fundamentals/crud/read-operations/cursor/#:~:text=iterated%20through%20all%20the%20documents>
=> DOCSP-38266: correct though to through on cursor page

source/index.txt, source/quick-start.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-38547
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/java/DOCSP-38547-quickstart-title/quick-start/
=> DOCSP-38547 Standardize Quick Start Title

source/upgrade.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-38949
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/java/DOCSP-38949-broken-upgrade-lins/upgrade/#version-4.8-server-release-support-changes
=> DOCSP-38949 Update broken links

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-38784
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-38784-whats-new-retries/whats-new/#std-label-version-5.1
=> DOCSP-38784: Sharded cluster retries

source/whats-new.txt
This reverts commit 43ab2e3d5f3c936a8a836f1663f097fbbdeb8ef8.
Reverts https://jira.mongodb.org/browse/DOCSP-38784, due to [this](https://mongodb.slack.com/archives/CTBGR14QN/p1714497529174319) Slack conversation
=> Revert "DOCSP-38784: Sharded cluster retries (#539)"

source/fundamentals/builders/updates.txt, source/includes/fundamentals/code-snippets/builders/Updates.java
JIRA - <https://jira.mongodb.org/browse/DOCSP-35926>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java/DOCSP-35926-surface-combine-section/fundamentals/builders/updates/
=> DOCSP-35926: surface combine information

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39269
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-39269-oidc-whats-new/whats-new/#what-s-new-in-5.1
=> DOCSP-39269: Add OIDC to What's New

source/fundamentals/connection/mongoclientsettings.txt, source/fundamentals/gridfs.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-4079
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-4079-gridfs-write-concern/fundamentals/gridfs/#store-files
=> DOCSP-4079: GridFS write concern

source/fundamentals/enterprise-auth.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39884
Staging - https://preview-mongodbmongokart.gatsbyjs.io/java/docsp-39884-gcp-vm/fundamentals/enterprise-auth/#mongodb-oidc
=> DOCSP-39884 - Google Compute Engine

source/connection-troubleshooting.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40887
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/java/DOCSP-40887-fix-note/connection-troubleshooting/
=> DOCSP-40887: Fix Connection Troubleshooting note

source/fundamentals/encrypt-fields.txt, source/includes/fundamentals/code-snippets/crypt-gradle-versioned.rst, source/includes/fundamentals/code-snippets/crypt-maven-versioned.rst, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43906>
Staging:
- [whats new](https://deploy-preview-575--docs-java.netlify.app/whats-new/#what-s-new-in-5.2)
- [encryption page](https://deploy-preview-575--docs-java.netlify.app/fundamentals/encrypt-fields/)
=> DOCSP-43906: crypt shared embedding

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45038
Staging - https://deploy-preview-587--docs-java.netlify.app/whats-new/#std-label-java-version-5.2.1
=> DOSCP-45038 UnsatisfiedLinkError fix

source/fundamentals.txt, source/fundamentals/builders.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/data-formats.txt, source/index.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/update-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44901>
Staging - <https://deploy-preview-589--docs-java.netlify.app/>
=> DOCSP-44901 TOC Relabel

source/fundamentals.txt, source/fundamentals/builders.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/data-formats.txt, source/index.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/update-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
=> [Backport v5.2] DOCSP-44901 TOC Relabel

.github/workflows/backport.yml, source/fundamentals.txt, source/fundamentals/builders.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/data-formats.txt, source/index.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/update-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
=> [Backport v5.0] DOCSP-44902 Shorten TOC

source/fundamentals.txt, source/fundamentals/builders.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/data-formats.txt, source/index.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/update-operations.txt
* delete 'one/many' changes
(cherry picked from commit b9819b038374a00a1de3705568e1f9b555321a55)
* DOCSP-44901 TOC Relabel
(cherry picked from commit c08fb6cac465dafdda42d874613803dcd066cb6d)
* remaining changes
* add back page bullets
(cherry picked from commit 418963b1c794628f1f854d4631edd867c364fcd3)
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
=> [Backport v4.10][Backport v5.2] DOCSP-44901 TOC Relabel (#593)

config/redirects
=> DOCSP-46473: Add symlinks for redirects

.github/pull_request_template.md, .github/workflows/add-netlify-links.yml
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
=> [Java Sync] Add Github action to add Netlify links to PR desc

source/data-formats/codecs.txt, source/data-formats/pojo-customization.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-47045
<li><a href=https://deploy-preview-652--docs-java.netlify.app/data-formats/codecs>data-formats/codecs</a></li><li><a href=https://deploy-preview-652--docs-java.netlify.app/data-formats/pojo-customization>data-formats/pojo-customization</a></li>
=> DOCSP-47045: Serialization keywords

source/includes/fundamentals/code-snippets/auth-credentials-gssapi-properties.rst, source/includes/fundamentals/code-snippets/auth-credentials-gssapi-subject-key.rst, source/includes/fundamentals/code-snippets/auth-credentials-gssapi-ticket-cache.rst, source/includes/fundamentals/code-snippets/auth-credentials-gssapi.rst, source/includes/fundamentals/code-snippets/auth-credentials-ldap.rst, source/security/auth/kerberos.txt, source/security/auth/ldap.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48713>
<li><a href=https://deploy-preview-676--docs-java.netlify.app/security/auth/kerberos>security/auth/kerberos</a></li><li><a href=https://deploy-preview-676--docs-java.netlify.app/security/auth/ldap>security/auth/ldap</a></li>
=> DOCSP-48713 Update non-MongoDB credentials

source/includes/fundamentals/code-snippets/auth-credentials-gssapi-properties.rst, source/includes/fundamentals/code-snippets/auth-credentials-gssapi-subject-key.rst, source/includes/fundamentals/code-snippets/auth-credentials-gssapi-ticket-cache.rst, source/includes/fundamentals/code-snippets/auth-credentials-gssapi.rst, source/includes/fundamentals/code-snippets/auth-credentials-ldap.rst, source/security/enterprise-auth.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48713>
=> [Backport v5.3] DOCSP-48713 Update non-MongoDB credentials

config/redirects, source/index.txt, source/reference.txt, source/reference/legacy.txt, source/reference/release-notes.txt
Backport https://github.com/mongodb/docs-java/commit/861ddd76582d10e0b2626872a39e3b53ed3f0fb2 from https://github.com/mongodb/docs-java/pull/698.
=> Backport 861ddd7 from #698.

.backportrc.json
JIRA - <https://jira.mongodb.org/browse/DOCSP-49013>
=> Docsp-49013 Edit .backportrc.json file to reflect current versions

config/redirects, source/index.txt, source/reference.txt, source/reference/legacy.txt, source/reference/release-notes.txt
=> Backport #698 to v5.4

snooty.toml, source/aggregation/aggregation-examples.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-50750>
<li><a href=https://deploy-preview-714--docs-java.netlify.app/aggregation/aggregation-examples>aggregation/aggregation-examples</a></li>
=> DOCSP-50750: agg tutorial link

config/redirects
Fix write/read redirects to include links like the one on Jira. 
[Slack conversation](https://mongodb.slack.com/archives/C018UTGP23T/p1750879149440849)
JIRA - <https://jira.mongodb.org/browse/DOCSP-50728>
No pages to preview
=> DOCSP-50728 Java Sync Write/Read Redirects 
